//! Merged PHPStan settings to `celerrate.toml` text: the carry rules
//! for paths (relative, placeholder-free, glob-free, inside the root),
//! the committed level table (levels 0 to 5 remap the typed families
//! to "warning"; 6 and above, and `max`, keep defaults), and the TOML
//! generation. The generated file must round-trip through
//! `celerrate_config` with zero diagnostics: that is the contract.

use super::settings::Settings;

/// The nine typed-family identifiers the level table remaps: the
/// `unknown-members`, `null-dereference`, and `argument-checks`
/// families, whole. Documented in `docs/migration.md` (drift-gated).
pub(crate) const REMAPPED_IDENTIFIERS: [&str; 9] = [
    "CEL0030", "CEL0031", "CEL0032", "CEL0033", "CEL0034", "CEL0035", "CEL0036", "CEL0037",
    "CEL0038",
];

/// The outcome of a conversion: the file text plus everything the
/// report needs to say about it.
#[derive(Debug)]
pub(crate) struct Conversion {
    pub(crate) toml: String,
    pub(crate) include: Vec<String>,
    pub(crate) exclude: Vec<String>,
    pub(crate) level_note: String,
    pub(crate) dropped: Vec<(String, &'static str)>,
}

pub(crate) fn convert(settings: &Settings) -> Conversion {
    let mut dropped = Vec::new();
    let include = carry(&settings.paths, &mut dropped);
    let exclude = carry(&settings.exclude_paths, &mut dropped);
    let (remapped, level_note) = severity_profile(settings.level.as_deref());
    let toml = generate(&include, &exclude, remapped);
    Conversion {
        toml,
        include,
        exclude,
        level_note,
        dropped,
    }
}

fn carry(paths: &[String], dropped: &mut Vec<(String, &'static str)>) -> Vec<String> {
    let mut carried: Vec<String> = Vec::new();
    for path in paths {
        match carriable(path) {
            Ok(clean) => {
                if !carried.contains(&clean) {
                    carried.push(clean);
                }
            }
            Err(reason) => dropped.push((path.clone(), reason)),
        }
    }
    carried
}

/// `celerrate.toml` accepts plain relative paths inside the root and
/// nothing else; everything narrower is dropped with its reason.
fn carriable(path: &str) -> Result<String, &'static str> {
    if path.contains('%') {
        return Err("NEON parameter placeholders are not resolved");
    }
    if path.starts_with('/')
        || path.starts_with('\\')
        || path.chars().nth(1).is_some_and(|second| second == ':')
    {
        return Err("absolute paths cannot be carried into celerrate.toml");
    }
    if path.contains('*') || path.contains('?') {
        return Err("glob patterns are not supported");
    }
    let clean = path.trim_end_matches('/');
    if clean.is_empty() {
        return Err("empty path");
    }
    if clean.split('/').any(|segment| segment == "..") {
        return Err("the path escapes the project root");
    }
    Ok(clean.to_owned())
}

/// The committed level table. Levels 0 to 5 (and a missing level,
/// PHPStan's default being 0) remap the typed families to "warning";
/// 6 and above, and `max`, keep default severities.
fn severity_profile(level: Option<&str>) -> (bool, String) {
    match level {
        None => (
            true,
            "no level found: PHPStan defaults to level 0; typed-family identifiers remapped to \"warning\""
                .to_owned(),
        ),
        Some("max") => (false, "level max: default severities kept".to_owned()),
        Some(text) => match text.parse::<u32>() {
            Ok(level) if level <= 5 => {
                (true, format!("level {level}: typed-family identifiers remapped to \"warning\""))
            }
            Ok(level) => (false, format!("level {level}: default severities kept")),
            Err(_) => (false, format!("level \"{text}\" not understood: default severities kept")),
        },
    }
}

const HEADER: &str = "\
# Generated by `celerrate migrate --from-phpstan`. Review and commit.
# Everything not set here keeps its default; `celerrate explain CELxxxx`
# documents any identifier.
";

fn generate(include: &[String], exclude: &[String], remapped: bool) -> String {
    let mut document = toml_edit::DocumentMut::new();
    if !include.is_empty() || !exclude.is_empty() {
        let mut project = toml_edit::Table::new();
        if !include.is_empty() {
            project.insert("include", toml_edit::value(string_array(include)));
        }
        if !exclude.is_empty() {
            project.insert("exclude", toml_edit::value(string_array(exclude)));
        }
        document.insert("project", toml_edit::Item::Table(project));
    }
    if remapped {
        let mut severity = toml_edit::Table::new();
        for identifier in REMAPPED_IDENTIFIERS {
            severity.insert(identifier, toml_edit::value("warning"));
        }
        document.insert("severity", toml_edit::Item::Table(severity));
    }
    format!("{HEADER}\n{document}")
}

fn string_array(values: &[String]) -> toml_edit::Array {
    values.iter().map(String::as_str).collect()
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::indexing_slicing, clippy::panic)]

    use super::*;
    use crate::migrate::settings::Settings;

    fn settings(paths: &[&str], excludes: &[&str], level: Option<&str>) -> Settings {
        Settings {
            paths: paths.iter().map(|path| (*path).to_owned()).collect(),
            exclude_paths: excludes.iter().map(|path| (*path).to_owned()).collect(),
            level: level.map(str::to_owned),
            ..Settings::default()
        }
    }

    #[test]
    fn paths_and_level_five_generate_project_and_severity_sections() {
        let conversion = convert(&settings(&["src", "tests"], &["src/Generated"], Some("5")));
        assert_eq!(conversion.include, ["src", "tests"]);
        assert_eq!(conversion.exclude, ["src/Generated"]);
        assert!(conversion.dropped.is_empty(), "{:?}", conversion.dropped);
        assert!(
            conversion.toml.contains("include = [\"src\", \"tests\"]"),
            "{}",
            conversion.toml
        );
        assert!(
            conversion.toml.contains("exclude = [\"src/Generated\"]"),
            "{}",
            conversion.toml
        );
        for identifier in REMAPPED_IDENTIFIERS {
            assert!(
                conversion
                    .toml
                    .contains(&format!("{identifier} = \"warning\"")),
                "missing {identifier} in:\n{}",
                conversion.toml
            );
        }
        assert!(
            conversion.level_note.contains("level 5"),
            "{}",
            conversion.level_note
        );
    }

    #[test]
    fn level_boundaries_follow_the_committed_table() {
        for (level, remapped) in [
            (None, true),
            (Some("0"), true),
            (Some("5"), true),
            (Some("6"), false),
            (Some("9"), false),
            (Some("max"), false),
            (Some("strict"), false),
        ] {
            let conversion = convert(&settings(&[], &[], level));
            assert_eq!(
                conversion.toml.contains("[severity]"),
                remapped,
                "level {level:?}:\n{}",
                conversion.toml
            );
        }
    }

    #[test]
    fn uncarriable_paths_are_dropped_with_reasons() {
        let conversion = convert(&settings(
            &[
                "/absolute",
                "%rootDir%/src",
                "src/*",
                "../outside",
                "src",
                "src",
            ],
            &[],
            Some("7"),
        ));
        // Deduplicated, only the honest survivor carries.
        assert_eq!(conversion.include, ["src"]);
        assert_eq!(conversion.dropped.len(), 4, "{:?}", conversion.dropped);
    }

    #[test]
    fn an_empty_conversion_still_generates_a_documented_header() {
        let conversion = convert(&settings(&[], &[], Some("max")));
        assert!(conversion.toml.starts_with('#'), "{}", conversion.toml);
        assert!(
            !conversion.toml.contains("[project]"),
            "{}",
            conversion.toml
        );
        assert!(
            !conversion.toml.contains("[severity]"),
            "{}",
            conversion.toml
        );
    }

    #[test]
    fn the_generated_file_round_trips_with_zero_configuration_diagnostics() {
        use std::collections::BTreeSet;

        let conversion = convert(&settings(&["src"], &["src/Generated"], Some("3")));
        let file = celerrate_source::FileId::new(0);
        let (configuration, parse_diagnostics) = celerrate_config::parse(file, &conversion.toml);
        assert!(
            parse_diagnostics.is_empty(),
            "{parse_diagnostics:?}\n{}",
            conversion.toml
        );
        let metadata: Vec<_> = celerrate_rules::core_rules()
            .into_iter()
            .map(|(metadata, _)| metadata)
            .collect();
        let known = celerrate_config::KnownSets {
            rule_names: metadata.iter().map(|rule| rule.name.as_str()).collect(),
            remappable_identifiers: metadata
                .iter()
                .flat_map(|rule| {
                    rule.identifiers
                        .iter()
                        .map(|identifier| identifier.id.as_str())
                })
                .collect(),
            registered_identifiers: celerrate_diagnostics::REGISTRY
                .iter()
                .map(|entry| entry.id.as_str())
                .collect::<BTreeSet<_>>(),
        };
        let validation = celerrate_config::validate(file, &configuration, &known);
        assert!(validation.is_empty(), "{validation:?}\n{}", conversion.toml);
    }
}
