[workspace]
resolver = "3"
members = ["crates/*", "xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
license = "MIT OR Apache-2.0"
authors = ["JDevelop"]
repository = "https://github.com/celerrate/celerrate"

[workspace.dependencies]
insta = { version = "1", features = ["glob"] }
rowan = "0.16"
salsa = "0.27"
tempfile = "3"
text-size = "1"
ungrammar = "1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
