//! Emits `crates/celerrate_syntax/src/ast/generated.rs`: one struct per
//! node rule with its `AstNode` impl and accessors, one Rust enum per
//! alternation rule, and the fieldless `ErrorNode` struct. Everything
//! calls into the hand-written `ast::support` plumbing.

use std::fmt::Write as _;

use super::grammar::{AstEnumSource, AstNodeSource, Cardinality, Field, FieldKind, GrammarSource};

pub fn ast_file(grammar: &GrammarSource) -> String {
    let mut text = String::new();
    text.push_str(
        "//! Generated by `cargo xtask codegen` from `php.ungram`; do not\n\
         //! edit by hand. Accessors return `Option` or an iterator: the\n\
         //! partial trees error recovery produces are normal citizens.\n\n\
         use super::{AstChildren, AstNode, support};\n\
         use crate::syntax_kind::SyntaxKind;\n\
         use crate::tree::{SyntaxNode, SyntaxToken};\n\n",
    );
    for node in &grammar.nodes {
        emit_node(&mut text, node);
    }
    emit_node(
        &mut text,
        &AstNodeSource {
            name: "ErrorNode".to_owned(),
            documentation: vec!["Recovery wreckage: tokens no grammar rule accepted.".to_owned()],
            fields: Vec::new(),
        },
    );
    for enumeration in &grammar.enums {
        emit_enum(&mut text, enumeration);
    }
    text
}

fn emit_node(text: &mut String, node: &AstNodeSource) {
    let name = &node.name;
    for line in &node.documentation {
        let _ = writeln!(text, "/// {line}");
    }
    let _ = writeln!(text, "#[derive(Debug, Clone, PartialEq, Eq, Hash)]");
    let _ = writeln!(text, "pub struct {name} {{");
    let _ = writeln!(text, "    syntax: SyntaxNode,");
    let _ = writeln!(text, "}}\n");
    let _ = writeln!(text, "impl AstNode for {name} {{");
    let _ = writeln!(text, "    fn can_cast(kind: SyntaxKind) -> bool {{");
    let _ = writeln!(text, "        kind == SyntaxKind::{name}");
    let _ = writeln!(text, "    }}");
    let _ = writeln!(text, "    fn cast(syntax: SyntaxNode) -> Option<Self> {{");
    let _ = writeln!(
        text,
        "        Self::can_cast(syntax.kind()).then(|| Self {{ syntax }})"
    );
    let _ = writeln!(text, "    }}");
    let _ = writeln!(text, "    fn syntax(&self) -> &SyntaxNode {{");
    let _ = writeln!(text, "        &self.syntax");
    let _ = writeln!(text, "    }}");
    let _ = writeln!(text, "}}\n");
    if node.fields.is_empty() {
        return;
    }
    let _ = writeln!(text, "impl {name} {{");
    for field in &node.fields {
        emit_accessor(text, field);
    }
    let _ = writeln!(text, "}}\n");
}

fn emit_accessor(text: &mut String, field: &Field) {
    let name = &field.name;
    match &field.kind {
        FieldKind::Node {
            type_name,
            cardinality: Cardinality::Many,
            ..
        } => {
            let _ = writeln!(
                text,
                "    pub fn {name}(&self) -> AstChildren<{type_name}> {{"
            );
            let _ = writeln!(text, "        support::children(self.syntax())");
            let _ = writeln!(text, "    }}");
        }
        FieldKind::Node {
            type_name,
            cardinality: Cardinality::Optional,
            index,
        } => {
            let _ = writeln!(text, "    pub fn {name}(&self) -> Option<{type_name}> {{");
            let _ = writeln!(text, "        support::child(self.syntax(), {index})");
            let _ = writeln!(text, "    }}");
        }
        FieldKind::Token { variants } => {
            let kinds = variants
                .iter()
                .map(|variant| format!("SyntaxKind::{variant}"))
                .collect::<Vec<String>>()
                .join(", ");
            let _ = writeln!(
                text,
                "    pub fn {name}_token(&self) -> Option<SyntaxToken> {{"
            );
            let _ = writeln!(text, "        support::token(self.syntax(), &[{kinds}])");
            let _ = writeln!(text, "    }}");
        }
    }
}

fn emit_enum(text: &mut String, enumeration: &AstEnumSource) {
    let name = &enumeration.name;
    if enumeration.documentation.is_empty() {
        let _ = writeln!(text, "/// The `{name}` alternation of `php.ungram`.");
    }
    for line in &enumeration.documentation {
        let _ = writeln!(text, "/// {line}");
    }
    let _ = writeln!(text, "// Variant names mirror node kind names on purpose.");
    let _ = writeln!(text, "#[allow(clippy::enum_variant_names)]");
    let _ = writeln!(text, "#[derive(Debug, Clone, PartialEq, Eq, Hash)]");
    let _ = writeln!(text, "pub enum {name} {{");
    for variant in &enumeration.variants {
        let _ = writeln!(text, "    {variant}({variant}),");
    }
    let _ = writeln!(text, "}}\n");
    let _ = writeln!(text, "impl AstNode for {name} {{");
    let _ = writeln!(text, "    fn can_cast(kind: SyntaxKind) -> bool {{");
    let kinds = enumeration
        .variants
        .iter()
        .map(|variant| format!("SyntaxKind::{variant}"))
        .collect::<Vec<String>>()
        .join(" | ");
    let _ = writeln!(text, "        matches!(kind, {kinds})");
    let _ = writeln!(text, "    }}");
    let _ = writeln!(text, "    fn cast(syntax: SyntaxNode) -> Option<Self> {{");
    let _ = writeln!(text, "        let result = match syntax.kind() {{");
    for variant in &enumeration.variants {
        let _ = writeln!(
            text,
            "            SyntaxKind::{variant} => Self::{variant}({variant} {{ syntax }}),"
        );
    }
    let _ = writeln!(text, "            _ => return None,");
    let _ = writeln!(text, "        }};");
    let _ = writeln!(text, "        Some(result)");
    let _ = writeln!(text, "    }}");
    let _ = writeln!(text, "    fn syntax(&self) -> &SyntaxNode {{");
    let _ = writeln!(text, "        match self {{");
    for variant in &enumeration.variants {
        let _ = writeln!(text, "            Self::{variant}(node) => node.syntax(),");
    }
    let _ = writeln!(text, "        }}");
    let _ = writeln!(text, "    }}");
    let _ = writeln!(text, "}}\n");
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used, clippy::unwrap_used, clippy::indexing_slicing)]

    use super::ast_file;
    use crate::codegen::grammar::load;

    const MINI: &str = "Root = Item*\nItem = name:'identifier' operator:('+' | '-') Root?\nExpression = Root | Item";

    #[test]
    fn the_emission_contains_structs_accessors_and_enums() {
        let grammar = load(MINI).expect("mini grammar loads");
        let text = ast_file(&grammar);
        assert!(text.starts_with("//! Generated by `cargo xtask codegen`"));
        assert!(text.contains("pub struct Root {"));
        assert!(text.contains("pub fn items(&self) -> AstChildren<Item> {"));
        assert!(text.contains("pub fn name_token(&self) -> Option<SyntaxToken> {"));
        assert!(
            text.contains("support::token(self.syntax(), &[SyntaxKind::Plus, SyntaxKind::Minus])")
        );
        assert!(text.contains("pub fn root(&self) -> Option<Root> {"));
        assert!(text.contains("support::child(self.syntax(), 0)"));
        assert!(text.contains("pub enum Expression {"));
        assert!(text.contains("#[allow(clippy::enum_variant_names)]"));
        assert!(text.contains("SyntaxKind::Item => Self::Item(Item { syntax }),"));
        assert!(text.contains("pub struct ErrorNode {"));
    }
}
