//! Emits `crates/celerrate_syntax/src/syntax_kind/generated.rs`: the
//! whole `SyntaxKind` enum (tokens from the table, nodes from
//! `php.ungram`, `ErrorNode` appended) plus the raw `u16` conversion.
//! The single variant list drives both the enum and `ALL`, so the
//! discriminant order and the conversion can never drift apart.

use std::fmt::Write as _;

use super::grammar::GrammarSource;
use super::tokens::TOKEN_KINDS;

pub fn syntax_kind_file(grammar: &GrammarSource) -> String {
    let mut variants: Vec<(String, Vec<String>)> = Vec::new();
    for definition in TOKEN_KINDS {
        variants.push((
            definition.variant.to_owned(),
            definition
                .documentation
                .iter()
                .map(|line| (*line).to_owned())
                .collect(),
        ));
    }
    let first_node = variants.len();
    for node in &grammar.nodes {
        variants.push((node.name.clone(), node.documentation.clone()));
    }
    variants.push((
        "ErrorNode".to_owned(),
        vec!["Recovery wreckage: tokens no grammar rule accepted.".to_owned()],
    ));

    let mut text = String::new();
    text.push_str(
        "//! Generated by `cargo xtask codegen`; do not edit by hand.\n\
         //! Token kinds come from xtask's token table, node kinds from\n\
         //! `php.ungram` (`ErrorNode` appended by the generator).\n\n",
    );
    text.push_str(
        "/// Every kind of token and node in PHP syntax.\n\
         ///\n\
         /// One vocabulary shared by the whole syntax layer, `#[repr(u16)]`\n\
         /// so the rowan tree stores it directly. Token kinds first, node\n\
         /// kinds after them.\n\
         ///\n\
         /// Keywords each get their own kind, resolved case-insensitively by\n\
         /// the lexer. Semi-reserved uses (`$object->list()`, `const FOR = 1;`,\n\
         /// `enum` as a plain name) are the parser's business: it re-treats\n\
         /// keyword kinds as identifiers where the grammar allows. `true`,\n\
         /// `false`, `null`, `self`, `parent`, and the magic constants are\n\
         /// plain identifiers, resolved semantically.\n",
    );
    text.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    text.push_str("#[repr(u16)]\n");
    text.push_str("pub enum SyntaxKind {\n");
    for (position, (variant, documentation)) in variants.iter().enumerate() {
        if position == first_node {
            text.push_str("    // Node kinds, owned by php.ungram.\n");
        }
        for line in documentation {
            let _ = writeln!(text, "    /// {line}");
        }
        let _ = writeln!(text, "    {variant},");
    }
    text.push_str("}\n\n");
    text.push_str("impl SyntaxKind {\n");
    text.push_str("    /// Every kind, in declaration (and therefore discriminant) order.\n");
    text.push_str("    const ALL: &[SyntaxKind] = &[\n");
    for (variant, _documentation) in &variants {
        let _ = writeln!(text, "        SyntaxKind::{variant},");
    }
    text.push_str("    ];\n\n");
    text.push_str("    /// The inverse of [`SyntaxKind::into_raw`]. Total and panic-free:\n");
    text.push_str("    /// out-of-range values return `None`.\n");
    text.push_str("    pub fn from_raw(raw: u16) -> Option<Self> {\n");
    text.push_str("        Self::ALL.get(usize::from(raw)).copied()\n");
    text.push_str("    }\n\n");
    text.push_str("    /// The `u16` the tree stores; the discriminant.\n");
    text.push_str("    pub fn into_raw(self) -> u16 {\n");
    text.push_str("        self as u16\n");
    text.push_str("    }\n");
    text.push_str("}\n");
    text
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used, clippy::unwrap_used, clippy::indexing_slicing)]

    use super::syntax_kind_file;
    use crate::codegen::grammar::load;

    #[test]
    fn the_emission_contains_tokens_nodes_and_the_raw_conversion() {
        let grammar = load("/// The root.\nRoot = Item*\nItem = 'identifier'").expect("loads");
        let text = syntax_kind_file(&grammar);
        // Token section, from the table, docs included.
        assert!(text.contains("    Whitespace,\n"));
        assert!(text.contains("/// `exit` and its alias `die`."));
        // Node section, from the grammar, docs included, ErrorNode last.
        assert!(text.contains("/// The root.\n    Root,\n"));
        let root_position = text.find("    Root,").expect("Root emitted");
        let error_node_position = text.find("    ErrorNode,").expect("ErrorNode emitted");
        assert!(root_position < error_node_position);
        // The raw conversion and its backing list.
        assert!(text.contains("const ALL: &[SyntaxKind]"));
        assert!(text.contains("pub fn from_raw(raw: u16) -> Option<Self>"));
        assert!(text.contains("SyntaxKind::Root,"));
        // The do-not-edit banner.
        assert!(text.starts_with("//! Generated by `cargo xtask codegen`"));
    }
}
