//! Compiled phpstorm-stubs: the embedded index of standard-library and
//! extension symbols with per-version availability metadata.
//!
//! A pinned snapshot of phpstorm-stubs is compiled by the feature-gated
//! `stub-compiler` binary (driven by `cargo xtask compile-stubs`) into a
//! committed, versioned binary blob. At runtime the embedded blob loads
//! as a high-durability salsa input and a tracked query filters it by
//! the project's PHP version range.

mod blob;
mod index;
mod query;
mod signature;
mod symbol;

#[cfg(any(test, feature = "compiler"))]
pub mod compiler;

pub use blob::{
    BLOB_FORMAT_VERSION, BLOB_MAGIC, SECTION_OVERLAYS, SECTION_SIGNATURES, SECTION_SYMBOL_TABLE,
    StubBlobError, decode, encode,
};
pub use index::StubIndex;
pub use query::{StubIndexInput, stubs_in_range};
pub use signature::{
    StubClassSurface, StubMember, StubMemberKind, StubParameter, StubSignature, StubVisibility,
    VersionedTypeText,
};
pub use symbol::{StubAvailability, StubDeprecation, StubSymbol, StubSymbolKind};

/// The committed stub blob, embedded at compile time. Regenerated by
/// `cargo xtask compile-stubs`; the freshness test and the CI `stubs`
/// job keep it in step with the pinned snapshot.
pub const EMBEDDED_STUB_BLOB: &[u8] = include_bytes!("stubs.bin");

/// Decodes the embedded blob. In a healthy build this cannot fail (the
/// freshness test compares the committed bytes to a recompilation); a
/// failure is surfaced as a value for the composition root to report,
/// never a panic.
pub fn embedded_stub_index() -> Result<StubIndex, StubBlobError> {
    blob::decode(EMBEDDED_STUB_BLOB)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::panic, clippy::unwrap_used, clippy::indexing_slicing)]

    use crate::{StubSymbolKind, embedded_stub_index};

    #[test]
    fn the_embedded_blob_decodes() {
        let index = embedded_stub_index();
        let index = match index {
            Ok(index) => index,
            Err(error) => panic!("the committed blob must decode: {error}"),
        };
        // Tens of thousands of symbols; a low floor keeps the test
        // honest without chasing the snapshot's exact count.
        assert!(index.len() > 10_000, "only {} symbols", index.len());
    }

    #[test]
    fn well_known_symbols_are_present_with_their_kinds() {
        let index = embedded_stub_index().unwrap_or_default();
        let find = |name: &str, kind: StubSymbolKind| {
            index
                .symbols()
                .iter()
                .any(|symbol| symbol.name == name && symbol.kind == kind)
        };
        assert!(find("strlen", StubSymbolKind::Function));
        assert!(find("Exception", StubSymbolKind::Class));
        assert!(find("Traversable", StubSymbolKind::Interface));
        assert!(
            find("E_ALL", StubSymbolKind::Constant),
            "define() extraction"
        );
        assert!(
            find("Random\\Randomizer", StubSymbolKind::Class),
            "namespaced extraction",
        );
    }

    #[test]
    fn the_embedded_blob_carries_the_signature_payload() {
        let index = crate::blob::decode(crate::EMBEDDED_STUB_BLOB).unwrap();
        assert!(!index.functions().is_empty(), "functions compiled");
        assert!(!index.classes().is_empty(), "class surfaces compiled");
    }

    #[test]
    fn corpus_spot_checks_hold_on_the_embedded_blob() {
        use celerrate_project::PhpVersion;
        let index = crate::blob::decode(crate::EMBEDDED_STUB_BLOB).unwrap();
        let function = |name: &str| {
            index
                .functions()
                .iter()
                .find(|(function_name, _)| function_name == name)
                .map(|(_, signature)| signature)
        };
        // strlen(string $string): int
        let strlen = function("strlen").unwrap();
        assert_eq!(
            strlen.parameters[0].type_text.at(PhpVersion::new(8, 1)),
            Some("string"),
        );
        assert_eq!(strlen.return_type.at(PhpVersion::new(8, 1)), Some("int"));
        // preg_match's $matches is by reference.
        let preg_match = function("preg_match").unwrap();
        let matches = preg_match
            .parameters
            .iter()
            .find(|parameter| parameter.name == "matches")
            .unwrap();
        assert!(matches.by_reference);
        // Exception::getMessage(): string, and the parent link to Throwable.
        let (_, exception) = index
            .classes()
            .iter()
            .find(|(name, _)| name == "Exception")
            .unwrap();
        assert!(exception.parents.iter().any(|parent| parent == "Throwable"));
        let get_message = exception
            .members
            .iter()
            .find(|member| member.name == "getMessage")
            .unwrap();
        assert_eq!(
            get_message
                .signature
                .as_ref()
                .unwrap()
                .return_type
                .at(PhpVersion::new(8, 1)),
            Some("string"),
        );
    }
}
