[package]
name = "celerrate_cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "celerrate"
path = "src/main.rs"

[dependencies]
blake3 = { workspace = true }
celerrate_db = { path = "../celerrate_db" }
celerrate_diagnostics = { path = "../celerrate_diagnostics" }
celerrate_edit = { path = "../celerrate_edit" }
celerrate_phpdoc_bridge = { path = "../celerrate_phpdoc_bridge" }
celerrate_plugin = { path = "../celerrate_plugin" }
celerrate_project = { path = "../celerrate_project" }
celerrate_rules = { path = "../celerrate_rules" }
celerrate_semantics = { path = "../celerrate_semantics" }
celerrate_source = { path = "../celerrate_source" }
celerrate_stdlib_provider = { path = "../celerrate_stdlib_provider" }
celerrate_stubs = { path = "../celerrate_stubs" }
celerrate_types = { path = "../celerrate_types" }
celerrate_vfs = { path = "../celerrate_vfs" }
clap = { workspace = true }
ctrlc = { workspace = true }
notify = { workspace = true }
postcard = { workspace = true }
rayon = { workspace = true }
salsa = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
blake3 = { workspace = true }
celerrate_syntax = { path = "../celerrate_syntax" }
insta = { workspace = true }
