//! The foreign-to-CEL correspondence table (design section 8): every
//! published identifier of both bridge dialects, triaged - mapped to a
//! non-empty set of Celerrate code strings, explicitly scope-wide, or
//! explicitly unmapped. Codes are plain strings; the matcher
//! downstream interns them, so this crate never grows an identifier
//! dependency. The vendored catalogues under `catalogues/` are the
//! evidence that "every" holds; the gate at the composition root
//! (`celerrate_cli/tests/suppression_correspondence.rs`) asserts table
//! and catalogue are the same set, both directions.
//!
//! Triage guideline: map when the foreign finding class overlaps a CEL
//! family's; over-suppression is the accepted direction; when in
//! doubt, `Unmapped` (the fallback widens to the whole scope, exactly
//! the pre-correspondence behavior).
//!
//! Review checklist: a new or changed `Codes` entry must come with (or
//! adjust) its per-code fixture in
//! `celerrate_cli/tests/suppressions.rs` (the
//! `every_mapped_phpstan_code_is_actually_suppressed_by_its_identifier`
//! and `every_mapped_psalm_code_is_actually_suppressed_by_its_identifier`
//! tables). The catalogue gate proves the table is complete and
//! transportable, never that a mapping is right; a wrong `Codes` entry
//! under-suppresses invisibly, and only the per-code fixture catches
//! that. That per-code gate also has a structural blind spot: its arm
//! list is derived from the codes present in each dialect's own table,
//! so a code reachable from one dialect but not the other is invisible
//! to the gate by construction. When a code is reachable from only one
//! side, ask whether the other dialect genuinely has no identifier for
//! it (a real gap in the upstream vocabulary) or whether a fold is
//! simply unmapped there (a gap in this table).

/// The two written dialects the bridge recognizes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Dialect {
    Phpstan,
    Psalm,
}

/// One foreign identifier's triage verdict.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ForeignMapping {
    /// Suppresses exactly these Celerrate codes.
    Codes(&'static [&'static str]),
    /// Explicitly suppresses the whole scope (`@psalm-suppress all`).
    ScopeWide,
    /// Triaged: Celerrate has no corresponding diagnostic (yet).
    Unmapped,
}

/// The triage verdict for one written identifier. Exact-case, per
/// dialect; an identifier absent from the table (a foreign tool's
/// newer release, a typo the foreign tool would reject too) is
/// unmapped, so the directive falls back to scope-wide suppression -
/// the user's decision is honored either way.
pub fn foreign_mapping(dialect: Dialect, identifier: &str) -> ForeignMapping {
    let table = correspondence_entries(dialect);
    table
        .binary_search_by(|(name, _)| (*name).cmp(identifier))
        .ok()
        .and_then(|position| table.get(position))
        .map(|(_, mapping)| *mapping)
        .unwrap_or(ForeignMapping::Unmapped)
}

/// The raw table, for the composition-root gate.
pub fn correspondence_entries(dialect: Dialect) -> &'static [(&'static str, ForeignMapping)] {
    match dialect {
        Dialect::Phpstan => PHPSTAN,
        Dialect::Psalm => PSALM,
    }
}

// The plan seeded class.deprecated too; it exists in neither the
// documented catalogue nor the search index (PHPStan spells the
// class-deprecation findings per reference site instead:
// new.deprecatedClass, parameter.deprecatedClass, and their
// siblings), so the seed is dropped rather than invented.
const PHPSTAN: &[(&str, ForeignMapping)] = &[
    ("argument.bitmaskNotAllowed", ForeignMapping::Unmapped),
    ("argument.byRef", ForeignMapping::Unmapped),
    ("argument.duplicate", ForeignMapping::Unmapped),
    ("argument.exclusiveConstants", ForeignMapping::Unmapped),
    ("argument.fscanf", ForeignMapping::Unmapped),
    ("argument.invalidConstant", ForeignMapping::Unmapped),
    ("argument.invalidPregQuote", ForeignMapping::Unmapped),
    ("argument.missing", ForeignMapping::Unmapped),
    ("argument.named", ForeignMapping::Unmapped),
    ("argument.namedNotSupported", ForeignMapping::Unmapped),
    ("argument.nonUnpackAfterUnpacked", ForeignMapping::Unmapped),
    (
        "argument.parameterRenamedInSubtype",
        ForeignMapping::Unmapped,
    ),
    ("argument.positionalAfterNamed", ForeignMapping::Unmapped),
    ("argument.printf", ForeignMapping::Unmapped),
    ("argument.sprintf", ForeignMapping::Unmapped),
    ("argument.sscanf", ForeignMapping::Unmapped),
    ("argument.staticClosure", ForeignMapping::Unmapped),
    ("argument.templateType", ForeignMapping::Unmapped),
    ("argument.type", ForeignMapping::Codes(&["CEL0035"])),
    ("argument.unknown", ForeignMapping::Codes(&["CEL0038"])),
    ("argument.unpackAfterNamed", ForeignMapping::Unmapped),
    ("argument.unpackNonIterable", ForeignMapping::Unmapped),
    ("argument.unresolvableType", ForeignMapping::Unmapped),
    ("argument.unused", ForeignMapping::Unmapped),
    ("argument.vprintf", ForeignMapping::Unmapped),
    ("argument.vsprintf", ForeignMapping::Unmapped),
    (
        "arguments.count",
        ForeignMapping::Codes(&["CEL0036", "CEL0037"]),
    ),
    ("array.duplicateKey", ForeignMapping::Unmapped),
    ("array.invalidKey", ForeignMapping::Unmapped),
    ("arrayFilter.alwaysEmpty", ForeignMapping::Unmapped),
    ("arrayFilter.empty", ForeignMapping::Unmapped),
    ("arrayFilter.same", ForeignMapping::Unmapped),
    ("arrayFilter.strict", ForeignMapping::Unmapped),
    ("arrayUnpacking.nonIterable", ForeignMapping::Unmapped),
    ("arrayUnpacking.stringOffset", ForeignMapping::Unmapped),
    ("arrayValues.empty", ForeignMapping::Unmapped),
    ("arrayValues.list", ForeignMapping::Unmapped),
    ("assert.alreadyNarrowedType", ForeignMapping::Unmapped),
    ("assert.deprecatedClass", ForeignMapping::Unmapped),
    ("assert.deprecatedEnum", ForeignMapping::Unmapped),
    ("assert.deprecatedInterface", ForeignMapping::Unmapped),
    ("assert.deprecatedTrait", ForeignMapping::Unmapped),
    ("assert.impossibleType", ForeignMapping::Unmapped),
    ("assert.internalClass", ForeignMapping::Unmapped),
    ("assert.internalEnum", ForeignMapping::Unmapped),
    ("assert.internalInterface", ForeignMapping::Unmapped),
    ("assert.internalTrait", ForeignMapping::Unmapped),
    ("assert.trait", ForeignMapping::Unmapped),
    ("assert.unknownExpr", ForeignMapping::Unmapped),
    ("assert.unresolvableType", ForeignMapping::Unmapped),
    ("assign.byRefForeachExpr", ForeignMapping::Unmapped),
    ("assign.invalidExpr", ForeignMapping::Unmapped),
    ("assign.propertyPrivateSet", ForeignMapping::Unmapped),
    ("assign.propertyProtectedSet", ForeignMapping::Unmapped),
    ("assign.propertyReadOnly", ForeignMapping::Unmapped),
    ("assign.propertyType", ForeignMapping::Unmapped),
    ("assign.readOnlyProperty", ForeignMapping::Unmapped),
    ("assign.readOnlyPropertyByPhpDoc", ForeignMapping::Unmapped),
    ("assign.staticPropertyPrivateSet", ForeignMapping::Unmapped),
    (
        "assign.staticPropertyProtectedSet",
        ForeignMapping::Unmapped,
    ),
    ("assign.this", ForeignMapping::Unmapped),
    ("assignOp.invalid", ForeignMapping::Unmapped),
    ("attribute.abstract", ForeignMapping::Unmapped),
    ("attribute.class", ForeignMapping::Unmapped),
    ("attribute.constructorNotPublic", ForeignMapping::Unmapped),
    ("attribute.deprecated", ForeignMapping::Unmapped),
    ("attribute.deprecatedClass", ForeignMapping::Unmapped),
    ("attribute.deprecatedEnum", ForeignMapping::Unmapped),
    ("attribute.deprecatedInterface", ForeignMapping::Unmapped),
    ("attribute.deprecatedTrait", ForeignMapping::Unmapped),
    ("attribute.enum", ForeignMapping::Unmapped),
    ("attribute.interface", ForeignMapping::Unmapped),
    ("attribute.internalClass", ForeignMapping::Unmapped),
    ("attribute.internalEnum", ForeignMapping::Unmapped),
    ("attribute.internalInterface", ForeignMapping::Unmapped),
    ("attribute.internalTrait", ForeignMapping::Unmapped),
    ("attribute.noConstructor", ForeignMapping::Unmapped),
    ("attribute.nonRepeatable", ForeignMapping::Unmapped),
    ("attribute.notAttribute", ForeignMapping::Unmapped),
    ("attribute.notFound", ForeignMapping::Unmapped),
    ("attribute.target", ForeignMapping::Unmapped),
    ("attribute.trait", ForeignMapping::Unmapped),
    ("attribute.unresolvableReturnType", ForeignMapping::Unmapped),
    ("attribute.void", ForeignMapping::Unmapped),
    ("backtick.deprecated", ForeignMapping::Unmapped),
    ("backtick.notAllowed", ForeignMapping::Unmapped),
    ("binaryOp.invalid", ForeignMapping::Unmapped),
    ("booleanAnd.alwaysFalse", ForeignMapping::Unmapped),
    ("booleanAnd.alwaysTrue", ForeignMapping::Unmapped),
    ("booleanAnd.leftAlwaysFalse", ForeignMapping::Unmapped),
    ("booleanAnd.leftAlwaysTrue", ForeignMapping::Unmapped),
    ("booleanAnd.leftNotBoolean", ForeignMapping::Unmapped),
    ("booleanAnd.resultUnused", ForeignMapping::Unmapped),
    ("booleanAnd.rightAlwaysFalse", ForeignMapping::Unmapped),
    ("booleanAnd.rightAlwaysTrue", ForeignMapping::Unmapped),
    ("booleanAnd.rightNotBoolean", ForeignMapping::Unmapped),
    ("booleanNot.alwaysFalse", ForeignMapping::Unmapped),
    ("booleanNot.alwaysTrue", ForeignMapping::Unmapped),
    ("booleanNot.exprNotBoolean", ForeignMapping::Unmapped),
    ("booleanOr.alwaysFalse", ForeignMapping::Unmapped),
    ("booleanOr.alwaysTrue", ForeignMapping::Unmapped),
    ("booleanOr.leftAlwaysFalse", ForeignMapping::Unmapped),
    ("booleanOr.leftAlwaysTrue", ForeignMapping::Unmapped),
    ("booleanOr.leftNotBoolean", ForeignMapping::Unmapped),
    ("booleanOr.resultUnused", ForeignMapping::Unmapped),
    ("booleanOr.rightAlwaysFalse", ForeignMapping::Unmapped),
    ("booleanOr.rightAlwaysTrue", ForeignMapping::Unmapped),
    ("booleanOr.rightNotBoolean", ForeignMapping::Unmapped),
    ("break.outOfLoop", ForeignMapping::Unmapped),
    ("callable.inVoidCast", ForeignMapping::Unmapped),
    ("callable.inaccessibleMethod", ForeignMapping::Unmapped),
    ("callable.nonCallable", ForeignMapping::Unmapped),
    ("callable.notSupported", ForeignMapping::Unmapped),
    ("callable.resultDiscarded", ForeignMapping::Unmapped),
    ("callable.shadowTemplate", ForeignMapping::Unmapped),
    ("callable.unresolvableReturnType", ForeignMapping::Unmapped),
    ("callable.void", ForeignMapping::Unmapped),
    ("cast.bool", ForeignMapping::Unmapped),
    ("cast.deprecated", ForeignMapping::Unmapped),
    ("cast.double", ForeignMapping::Unmapped),
    ("cast.int", ForeignMapping::Unmapped),
    ("cast.string", ForeignMapping::Unmapped),
    ("cast.unset", ForeignMapping::Unmapped),
    ("cast.useless", ForeignMapping::Unmapped),
    ("cast.void", ForeignMapping::Unmapped),
    ("cast.voidNotSupported", ForeignMapping::Unmapped),
    ("catch.alreadyCaught", ForeignMapping::Unmapped),
    ("catch.deprecatedClass", ForeignMapping::Unmapped),
    ("catch.deprecatedEnum", ForeignMapping::Unmapped),
    ("catch.deprecatedInterface", ForeignMapping::Unmapped),
    ("catch.deprecatedTrait", ForeignMapping::Unmapped),
    ("catch.internalClass", ForeignMapping::Unmapped),
    ("catch.internalEnum", ForeignMapping::Unmapped),
    ("catch.internalInterface", ForeignMapping::Unmapped),
    ("catch.internalTrait", ForeignMapping::Unmapped),
    ("catch.neverThrown", ForeignMapping::Unmapped),
    ("catch.nonCapturingNotSupported", ForeignMapping::Unmapped),
    ("catch.notThrowable", ForeignMapping::Unmapped),
    (
        "class.allowDynamicPropertiesReadonly",
        ForeignMapping::Unmapped,
    ),
    ("class.deprecatedAttribute", ForeignMapping::Unmapped),
    ("class.disallowedSubtype", ForeignMapping::Unmapped),
    ("class.duplicate", ForeignMapping::Unmapped),
    ("class.duplicateConstant", ForeignMapping::Unmapped),
    ("class.duplicateEnumCase", ForeignMapping::Unmapped),
    ("class.duplicateMethod", ForeignMapping::Unmapped),
    ("class.duplicateProperty", ForeignMapping::Unmapped),
    ("class.extendsDeprecatedClass", ForeignMapping::Unmapped),
    ("class.extendsDeprecatedEnum", ForeignMapping::Unmapped),
    ("class.extendsDeprecatedInterface", ForeignMapping::Unmapped),
    ("class.extendsDeprecatedTrait", ForeignMapping::Unmapped),
    ("class.extendsEnum", ForeignMapping::Unmapped),
    ("class.extendsFinal", ForeignMapping::Unmapped),
    ("class.extendsFinalByPhpDoc", ForeignMapping::Unmapped),
    ("class.extendsInterface", ForeignMapping::Unmapped),
    ("class.extendsInternalClass", ForeignMapping::Unmapped),
    ("class.extendsInternalEnum", ForeignMapping::Unmapped),
    ("class.extendsInternalInterface", ForeignMapping::Unmapped),
    ("class.extendsInternalTrait", ForeignMapping::Unmapped),
    ("class.extendsNetteObject", ForeignMapping::Unmapped),
    ("class.extendsTrait", ForeignMapping::Unmapped),
    ("class.implementsDeprecatedClass", ForeignMapping::Unmapped),
    ("class.implementsDeprecatedEnum", ForeignMapping::Unmapped),
    (
        "class.implementsDeprecatedInterface",
        ForeignMapping::Unmapped,
    ),
    ("class.implementsDeprecatedTrait", ForeignMapping::Unmapped),
    ("class.implementsInternalClass", ForeignMapping::Unmapped),
    ("class.implementsInternalEnum", ForeignMapping::Unmapped),
    (
        "class.implementsInternalInterface",
        ForeignMapping::Unmapped,
    ),
    ("class.implementsInternalTrait", ForeignMapping::Unmapped),
    ("class.missingExtends", ForeignMapping::Unmapped),
    ("class.missingImplements", ForeignMapping::Unmapped),
    ("class.nameCase", ForeignMapping::Unmapped),
    ("class.nameInUse", ForeignMapping::Unmapped),
    ("class.noParent", ForeignMapping::Unmapped),
    ("class.nonReadOnly", ForeignMapping::Unmapped),
    // PHPStan folds two different resolution outcomes into one "not
    // found" identifier. CEL0018/CEL0019/CEL0020 fire when a reference
    // resolves nowhere at all, in the project, its Composer
    // dependencies, or the bundled stubs. CEL0021 and CEL0022 fire on
    // a different outcome: the reference does resolve through the
    // stubs, but its availability window falls outside the project's
    // configured PHP version range (CEL0021 when the symbol is not
    // yet available at the minimum version, CEL0022 when it was
    // already removed by the maximum version). PHPStan has no
    // separate identifier for that version-window case, so
    // `class.notFound`, `function.notFound`, and `constant.notFound`
    // below must each widen to all three codes. Narrowing to only the
    // unknown-symbol code would under-suppress: `@phpstan-ignore
    // function.notFound` written over a call Celerrate reports as
    // CEL0022 would see the diagnostic reappear once the directive is
    // matched against a single narrower code, and under-suppression
    // is the one failure direction this project treats as a defect.
    // Do not shrink these back to one code.
    (
        "class.notFound",
        ForeignMapping::Codes(&["CEL0018", "CEL0021", "CEL0022"]),
    ),
    ("class.prefixed", ForeignMapping::Unmapped),
    ("class.readOnly", ForeignMapping::Unmapped),
    ("class.serializable", ForeignMapping::Unmapped),
    ("class.toStringDeprecated", ForeignMapping::Unmapped),
    ("classConstant.class", ForeignMapping::Unmapped),
    (
        "classConstant.deprecated",
        ForeignMapping::Codes(&["CEL0023"]),
    ),
    ("classConstant.deprecatedClass", ForeignMapping::Unmapped),
    ("classConstant.deprecatedEnum", ForeignMapping::Unmapped),
    (
        "classConstant.deprecatedInterface",
        ForeignMapping::Unmapped,
    ),
    ("classConstant.deprecatedTrait", ForeignMapping::Unmapped),
    ("classConstant.dynamicFetch", ForeignMapping::Unmapped),
    ("classConstant.dynamicString", ForeignMapping::Unmapped),
    ("classConstant.final", ForeignMapping::Unmapped),
    ("classConstant.finalNotSupported", ForeignMapping::Unmapped),
    ("classConstant.finalPrivate", ForeignMapping::Unmapped),
    ("classConstant.inTrait", ForeignMapping::Unmapped),
    ("classConstant.internal", ForeignMapping::Unmapped),
    ("classConstant.internalClass", ForeignMapping::Unmapped),
    ("classConstant.internalEnum", ForeignMapping::Unmapped),
    ("classConstant.internalInterface", ForeignMapping::Unmapped),
    ("classConstant.internalTrait", ForeignMapping::Unmapped),
    ("classConstant.missingNativeType", ForeignMapping::Unmapped),
    ("classConstant.nameNotString", ForeignMapping::Unmapped),
    ("classConstant.nameType", ForeignMapping::Unmapped),
    ("classConstant.nativeType", ForeignMapping::Unmapped),
    (
        "classConstant.nativeTypeNotSupported",
        ForeignMapping::Unmapped,
    ),
    ("classConstant.nonFinal", ForeignMapping::Unmapped),
    ("classConstant.nonObject", ForeignMapping::Unmapped),
    (
        "classConstant.notFound",
        ForeignMapping::Codes(&["CEL0032"]),
    ),
    ("classConstant.notSupported", ForeignMapping::Unmapped),
    ("classConstant.onTrait", ForeignMapping::Unmapped),
    ("classConstant.phpDocType", ForeignMapping::Unmapped),
    ("classConstant.private", ForeignMapping::Unmapped),
    ("classConstant.protected", ForeignMapping::Unmapped),
    ("classConstant.type", ForeignMapping::Unmapped),
    ("classConstant.unresolvableType", ForeignMapping::Unmapped),
    ("classConstant.unused", ForeignMapping::Unmapped),
    ("classConstant.value", ForeignMapping::Unmapped),
    ("classConstant.visibility", ForeignMapping::Unmapped),
    ("classImplements.class", ForeignMapping::Unmapped),
    ("classImplements.enum", ForeignMapping::Unmapped),
    ("classImplements.trait", ForeignMapping::Unmapped),
    ("clone.nonObject", ForeignMapping::Unmapped),
    ("closure.unusedUse", ForeignMapping::Unmapped),
    ("closure.useDuplicate", ForeignMapping::Unmapped),
    ("closure.useSuperGlobal", ForeignMapping::Unmapped),
    ("closure.useThis", ForeignMapping::Unmapped),
    ("conditionalType.alwaysFalse", ForeignMapping::Unmapped),
    ("conditionalType.alwaysTrue", ForeignMapping::Unmapped),
    ("conditionalType.subjectNotFound", ForeignMapping::Unmapped),
    ("consistentConstructor.private", ForeignMapping::Unmapped),
    ("constant.attributesNotSupported", ForeignMapping::Unmapped),
    ("constant.attributesRuleCannotRun", ForeignMapping::Unmapped),
    ("constant.defineValue", ForeignMapping::Unmapped),
    ("constant.deprecated", ForeignMapping::Codes(&["CEL0023"])),
    (
        "constant.notFound",
        ForeignMapping::Codes(&["CEL0020", "CEL0021", "CEL0022"]),
    ),
    ("constant.value", ForeignMapping::Unmapped),
    ("constructor.call", ForeignMapping::Unmapped),
    ("constructor.missingParentCall", ForeignMapping::Unmapped),
    ("constructor.returnType", ForeignMapping::Unmapped),
    ("constructor.unusedParameter", ForeignMapping::Unmapped),
    ("continue.outOfLoop", ForeignMapping::Unmapped),
    ("deadCode.unreachable", ForeignMapping::Unmapped),
    ("declareStrictTypes.notFirst", ForeignMapping::Unmapped),
    ("declareStrictTypes.value", ForeignMapping::Unmapped),
    ("div.leftNonNumeric", ForeignMapping::Unmapped),
    ("div.rightNonNumeric", ForeignMapping::Unmapped),
    ("doWhile.alwaysFalse", ForeignMapping::Unmapped),
    ("doWhile.alwaysTrue", ForeignMapping::Unmapped),
    ("doWhile.condNotBoolean", ForeignMapping::Unmapped),
    ("doctrine.associationType", ForeignMapping::Unmapped),
    ("doctrine.columnType", ForeignMapping::Unmapped),
    ("doctrine.countArgument", ForeignMapping::Unmapped),
    ("doctrine.descriptorNotFound", ForeignMapping::Unmapped),
    ("doctrine.dql", ForeignMapping::Unmapped),
    ("doctrine.enumType", ForeignMapping::Unmapped),
    ("doctrine.finalConstructor", ForeignMapping::Unmapped),
    ("doctrine.finalEntity", ForeignMapping::Unmapped),
    ("doctrine.findByArgument", ForeignMapping::Unmapped),
    ("doctrine.findOneByArgument", ForeignMapping::Unmapped),
    ("doctrine.internalError", ForeignMapping::Unmapped),
    ("doctrine.mapping", ForeignMapping::Unmapped),
    ("doctrine.queryBuilderDynamic", ForeignMapping::Unmapped),
    (
        "doctrine.queryBuilderDynamicArgument",
        ForeignMapping::Unmapped,
    ),
    ("echo.nonString", ForeignMapping::Unmapped),
    ("elseif.alwaysFalse", ForeignMapping::Unmapped),
    ("elseif.alwaysTrue", ForeignMapping::Unmapped),
    ("elseif.condNotBoolean", ForeignMapping::Unmapped),
    ("empty.expr", ForeignMapping::Unmapped),
    ("empty.initializedProperty", ForeignMapping::Unmapped),
    ("empty.notAllowed", ForeignMapping::Unmapped),
    ("empty.offset", ForeignMapping::Unmapped),
    ("empty.property", ForeignMapping::Unmapped),
    ("empty.variable", ForeignMapping::Unmapped),
    ("encapsedStringPart.nonString", ForeignMapping::Unmapped),
    ("enum.allowDynamicProperties", ForeignMapping::Unmapped),
    ("enum.backingType", ForeignMapping::Unmapped),
    ("enum.caseOutsideOfEnum", ForeignMapping::Unmapped),
    ("enum.caseType", ForeignMapping::Unmapped),
    ("enum.caseWithValue", ForeignMapping::Unmapped),
    ("enum.constructor", ForeignMapping::Unmapped),
    ("enum.deprecatedAttribute", ForeignMapping::Unmapped),
    ("enum.destructor", ForeignMapping::Unmapped),
    ("enum.disallowedSubtype", ForeignMapping::Unmapped),
    ("enum.duplicate", ForeignMapping::Unmapped),
    ("enum.duplicateConstant", ForeignMapping::Unmapped),
    ("enum.duplicateEnumCase", ForeignMapping::Unmapped),
    ("enum.duplicateMethod", ForeignMapping::Unmapped),
    ("enum.duplicateProperty", ForeignMapping::Unmapped),
    ("enum.duplicateValue", ForeignMapping::Unmapped),
    ("enum.generic", ForeignMapping::Unmapped),
    ("enum.implementsDeprecatedClass", ForeignMapping::Unmapped),
    ("enum.implementsDeprecatedEnum", ForeignMapping::Unmapped),
    (
        "enum.implementsDeprecatedInterface",
        ForeignMapping::Unmapped,
    ),
    ("enum.implementsDeprecatedTrait", ForeignMapping::Unmapped),
    ("enum.implementsInternalClass", ForeignMapping::Unmapped),
    ("enum.implementsInternalEnum", ForeignMapping::Unmapped),
    ("enum.implementsInternalInterface", ForeignMapping::Unmapped),
    ("enum.implementsInternalTrait", ForeignMapping::Unmapped),
    ("enum.magicMethod", ForeignMapping::Unmapped),
    ("enum.methodRedeclaration", ForeignMapping::Unmapped),
    ("enum.missingCase", ForeignMapping::Unmapped),
    ("enum.nameCase", ForeignMapping::Unmapped),
    ("enum.nameInUse", ForeignMapping::Unmapped),
    ("enum.serializable", ForeignMapping::Unmapped),
    ("enumImplements.class", ForeignMapping::Unmapped),
    ("enumImplements.enum", ForeignMapping::Unmapped),
    ("enumImplements.trait", ForeignMapping::Unmapped),
    ("equal.alwaysFalse", ForeignMapping::Unmapped),
    ("equal.alwaysTrue", ForeignMapping::Unmapped),
    ("equal.invalid", ForeignMapping::Unmapped),
    ("equal.notAllowed", ForeignMapping::Unmapped),
    ("expr.resultUnused", ForeignMapping::Unmapped),
    (
        "filterVar.nullOnFailureAndThrowOnFailure",
        ForeignMapping::Unmapped,
    ),
    ("finally.exitPoint", ForeignMapping::Unmapped),
    ("for.variableOverwrite", ForeignMapping::Unmapped),
    ("foreach.emptyArray", ForeignMapping::Unmapped),
    ("foreach.keyOverwrite", ForeignMapping::Unmapped),
    ("foreach.nonIterable", ForeignMapping::Unmapped),
    ("foreach.valueOverwrite", ForeignMapping::Unmapped),
    ("function.alreadyNarrowedType", ForeignMapping::Unmapped),
    ("function.deprecated", ForeignMapping::Codes(&["CEL0023"])),
    ("function.duplicate", ForeignMapping::Unmapped),
    ("function.impossibleHaystackValue", ForeignMapping::Unmapped),
    ("function.impossibleType", ForeignMapping::Unmapped),
    ("function.inVoidCast", ForeignMapping::Unmapped),
    ("function.inner", ForeignMapping::Unmapped),
    ("function.internal", ForeignMapping::Unmapped),
    ("function.nameCase", ForeignMapping::Unmapped),
    (
        "function.notFound",
        ForeignMapping::Codes(&["CEL0019", "CEL0021", "CEL0022"]),
    ),
    ("function.resultDiscarded", ForeignMapping::Unmapped),
    ("function.resultUnused", ForeignMapping::Unmapped),
    ("function.strict", ForeignMapping::Unmapped),
    ("function.unresolvableReturnType", ForeignMapping::Unmapped),
    ("function.uselessReturnValue", ForeignMapping::Unmapped),
    ("function.variance", ForeignMapping::Unmapped),
    ("function.void", ForeignMapping::Unmapped),
    ("generator.keyType", ForeignMapping::Unmapped),
    ("generator.nonIterable", ForeignMapping::Unmapped),
    ("generator.outOfFunction", ForeignMapping::Unmapped),
    ("generator.returnType", ForeignMapping::Unmapped),
    ("generator.sendType", ForeignMapping::Unmapped),
    ("generator.valueType", ForeignMapping::Unmapped),
    ("generator.void", ForeignMapping::Unmapped),
    (
        "generics.callSiteVarianceConflict",
        ForeignMapping::Unmapped,
    ),
    (
        "generics.callSiteVarianceNotAllowed",
        ForeignMapping::Unmapped,
    ),
    (
        "generics.callSiteVarianceRedundant",
        ForeignMapping::Unmapped,
    ),
    ("generics.deprecatedClassBound", ForeignMapping::Unmapped),
    ("generics.deprecatedClassDefault", ForeignMapping::Unmapped),
    ("generics.deprecatedEnumBound", ForeignMapping::Unmapped),
    ("generics.deprecatedEnumDefault", ForeignMapping::Unmapped),
    (
        "generics.deprecatedInterfaceBound",
        ForeignMapping::Unmapped,
    ),
    (
        "generics.deprecatedInterfaceDefault",
        ForeignMapping::Unmapped,
    ),
    ("generics.deprecatedTraitBound", ForeignMapping::Unmapped),
    ("generics.deprecatedTraitDefault", ForeignMapping::Unmapped),
    ("generics.existingClass", ForeignMapping::Unmapped),
    ("generics.existingTypeAlias", ForeignMapping::Unmapped),
    ("generics.interfaceConflict", ForeignMapping::Unmapped),
    ("generics.internalClassBound", ForeignMapping::Unmapped),
    ("generics.internalClassDefault", ForeignMapping::Unmapped),
    ("generics.internalEnumBound", ForeignMapping::Unmapped),
    ("generics.internalEnumDefault", ForeignMapping::Unmapped),
    ("generics.internalInterfaceBound", ForeignMapping::Unmapped),
    (
        "generics.internalInterfaceDefault",
        ForeignMapping::Unmapped,
    ),
    ("generics.internalTraitBound", ForeignMapping::Unmapped),
    ("generics.internalTraitDefault", ForeignMapping::Unmapped),
    ("generics.lessTypes", ForeignMapping::Unmapped),
    ("generics.moreTypes", ForeignMapping::Unmapped),
    ("generics.noParent", ForeignMapping::Unmapped),
    ("generics.notCompatible", ForeignMapping::Unmapped),
    ("generics.notGeneric", ForeignMapping::Unmapped),
    ("generics.notSubtype", ForeignMapping::Unmapped),
    ("generics.notSupportedBound", ForeignMapping::Unmapped),
    (
        "generics.requiredTypeAfterOptional",
        ForeignMapping::Unmapped,
    ),
    (
        "generics.templateDefaultOutOfBounds",
        ForeignMapping::Unmapped,
    ),
    ("generics.trait", ForeignMapping::Unmapped),
    ("generics.traitBound", ForeignMapping::Unmapped),
    ("generics.unresolvable", ForeignMapping::Unmapped),
    ("generics.variance", ForeignMapping::Unmapped),
    ("generics.wrongParent", ForeignMapping::Unmapped),
    ("global.this", ForeignMapping::Unmapped),
    ("goto.labelUndefined", ForeignMapping::Unmapped),
    ("greater.alwaysFalse", ForeignMapping::Unmapped),
    ("greater.alwaysTrue", ForeignMapping::Unmapped),
    ("greater.invalid", ForeignMapping::Unmapped),
    ("greaterOrEqual.alwaysFalse", ForeignMapping::Unmapped),
    ("greaterOrEqual.alwaysTrue", ForeignMapping::Unmapped),
    ("greaterOrEqual.invalid", ForeignMapping::Unmapped),
    ("identical.alwaysFalse", ForeignMapping::Unmapped),
    ("identical.alwaysTrue", ForeignMapping::Unmapped),
    ("if.alwaysFalse", ForeignMapping::Unmapped),
    ("if.alwaysTrue", ForeignMapping::Unmapped),
    ("if.condNotBoolean", ForeignMapping::Unmapped),
    ("ignore.allLineErrors", ForeignMapping::Unmapped),
    ("ignore.count", ForeignMapping::Unmapped),
    ("ignore.noComment", ForeignMapping::Unmapped),
    ("ignore.parseError", ForeignMapping::Unmapped),
    ("ignore.unmatched", ForeignMapping::Unmapped),
    ("ignore.unmatchedIdentifier", ForeignMapping::Unmapped),
    ("ignore.unmatchedLine", ForeignMapping::Unmapped),
    ("impure.betweenPhpTags", ForeignMapping::Unmapped),
    ("impure.die", ForeignMapping::Unmapped),
    ("impure.echo", ForeignMapping::Unmapped),
    ("impure.eval", ForeignMapping::Unmapped),
    ("impure.exit", ForeignMapping::Unmapped),
    ("impure.functionCall", ForeignMapping::Unmapped),
    ("impure.global", ForeignMapping::Unmapped),
    ("impure.include", ForeignMapping::Unmapped),
    ("impure.methodCall", ForeignMapping::Unmapped),
    ("impure.new", ForeignMapping::Unmapped),
    ("impure.print", ForeignMapping::Unmapped),
    ("impure.propertyAssign", ForeignMapping::Unmapped),
    ("impure.propertyAssignByRef", ForeignMapping::Unmapped),
    ("impure.propertyUnset", ForeignMapping::Unmapped),
    ("impure.require", ForeignMapping::Unmapped),
    ("impure.static", ForeignMapping::Unmapped),
    ("impure.staticPropertyAccess", ForeignMapping::Unmapped),
    ("impure.superglobal", ForeignMapping::Unmapped),
    ("impure.yield", ForeignMapping::Unmapped),
    ("impure.yieldFrom", ForeignMapping::Unmapped),
    ("impureFunction.pure", ForeignMapping::Unmapped),
    ("impureMethod.pure", ForeignMapping::Unmapped),
    ("include.fileNotFound", ForeignMapping::Unmapped),
    ("includeOnce.fileNotFound", ForeignMapping::Unmapped),
    ("instanceof.alwaysFalse", ForeignMapping::Unmapped),
    ("instanceof.alwaysTrue", ForeignMapping::Unmapped),
    ("instanceof.deprecatedClass", ForeignMapping::Unmapped),
    ("instanceof.deprecatedEnum", ForeignMapping::Unmapped),
    ("instanceof.deprecatedInterface", ForeignMapping::Unmapped),
    ("instanceof.deprecatedTrait", ForeignMapping::Unmapped),
    ("instanceof.internalClass", ForeignMapping::Unmapped),
    ("instanceof.internalEnum", ForeignMapping::Unmapped),
    ("instanceof.internalInterface", ForeignMapping::Unmapped),
    ("instanceof.internalTrait", ForeignMapping::Unmapped),
    ("instanceof.invalidExprType", ForeignMapping::Unmapped),
    ("instanceof.trait", ForeignMapping::Unmapped),
    ("interface.allowDynamicProperties", ForeignMapping::Unmapped),
    ("interface.deprecatedAttribute", ForeignMapping::Unmapped),
    ("interface.disallowedSubtype", ForeignMapping::Unmapped),
    ("interface.duplicate", ForeignMapping::Unmapped),
    ("interface.duplicateConstant", ForeignMapping::Unmapped),
    ("interface.duplicateEnumCase", ForeignMapping::Unmapped),
    ("interface.duplicateMethod", ForeignMapping::Unmapped),
    ("interface.duplicateProperty", ForeignMapping::Unmapped),
    ("interface.extendsDeprecatedClass", ForeignMapping::Unmapped),
    ("interface.extendsDeprecatedEnum", ForeignMapping::Unmapped),
    (
        "interface.extendsDeprecatedInterface",
        ForeignMapping::Unmapped,
    ),
    ("interface.extendsDeprecatedTrait", ForeignMapping::Unmapped),
    ("interface.extendsInternalClass", ForeignMapping::Unmapped),
    ("interface.extendsInternalEnum", ForeignMapping::Unmapped),
    (
        "interface.extendsInternalInterface",
        ForeignMapping::Unmapped,
    ),
    ("interface.extendsInternalTrait", ForeignMapping::Unmapped),
    ("interface.nameCase", ForeignMapping::Unmapped),
    ("interface.nameInUse", ForeignMapping::Unmapped),
    ("interface.notFound", ForeignMapping::Unmapped),
    ("interface.traitUse", ForeignMapping::Unmapped),
    ("interfaceExtends.class", ForeignMapping::Unmapped),
    ("interfaceExtends.enum", ForeignMapping::Unmapped),
    ("interfaceExtends.trait", ForeignMapping::Unmapped),
    ("isset.expr", ForeignMapping::Unmapped),
    ("isset.initializedProperty", ForeignMapping::Unmapped),
    ("isset.offset", ForeignMapping::Unmapped),
    ("isset.property", ForeignMapping::Unmapped),
    ("isset.variable", ForeignMapping::Unmapped),
    ("label.unused", ForeignMapping::Unmapped),
    ("logicalAnd.alwaysFalse", ForeignMapping::Unmapped),
    ("logicalAnd.alwaysTrue", ForeignMapping::Unmapped),
    ("logicalAnd.leftAlwaysFalse", ForeignMapping::Unmapped),
    ("logicalAnd.leftAlwaysTrue", ForeignMapping::Unmapped),
    ("logicalAnd.leftNotBoolean", ForeignMapping::Unmapped),
    ("logicalAnd.resultUnused", ForeignMapping::Unmapped),
    ("logicalAnd.rightAlwaysFalse", ForeignMapping::Unmapped),
    ("logicalAnd.rightAlwaysTrue", ForeignMapping::Unmapped),
    ("logicalAnd.rightNotBoolean", ForeignMapping::Unmapped),
    ("logicalOr.alwaysFalse", ForeignMapping::Unmapped),
    ("logicalOr.alwaysTrue", ForeignMapping::Unmapped),
    ("logicalOr.leftAlwaysFalse", ForeignMapping::Unmapped),
    ("logicalOr.leftAlwaysTrue", ForeignMapping::Unmapped),
    ("logicalOr.leftNotBoolean", ForeignMapping::Unmapped),
    ("logicalOr.resultUnused", ForeignMapping::Unmapped),
    ("logicalOr.rightAlwaysFalse", ForeignMapping::Unmapped),
    ("logicalOr.rightAlwaysTrue", ForeignMapping::Unmapped),
    ("logicalOr.rightNotBoolean", ForeignMapping::Unmapped),
    ("logicalXor.leftAlwaysFalse", ForeignMapping::Unmapped),
    ("logicalXor.leftAlwaysTrue", ForeignMapping::Unmapped),
    ("logicalXor.resultUnused", ForeignMapping::Unmapped),
    ("logicalXor.rightAlwaysFalse", ForeignMapping::Unmapped),
    ("logicalXor.rightAlwaysTrue", ForeignMapping::Unmapped),
    ("magicConstant.outOfClass", ForeignMapping::Unmapped),
    ("magicConstant.outOfFunction", ForeignMapping::Unmapped),
    ("magicConstant.outOfNamespace", ForeignMapping::Unmapped),
    ("magicConstant.outOfTrait", ForeignMapping::Unmapped),
    ("match.alwaysFalse", ForeignMapping::Unmapped),
    ("match.alwaysTrue", ForeignMapping::Unmapped),
    ("match.unhandled", ForeignMapping::Unmapped),
    ("match.void", ForeignMapping::Unmapped),
    ("method.abstract", ForeignMapping::Unmapped),
    (
        "method.abstractOverridingNonAbstract",
        ForeignMapping::Unmapped,
    ),
    ("method.abstractPrivate", ForeignMapping::Unmapped),
    ("method.alreadyNarrowedType", ForeignMapping::Unmapped),
    ("method.callToAbstract", ForeignMapping::Unmapped),
    ("method.childParameterType", ForeignMapping::Unmapped),
    ("method.childReturnType", ForeignMapping::Unmapped),
    ("method.deprecated", ForeignMapping::Codes(&["CEL0023"])),
    ("method.deprecatedClass", ForeignMapping::Unmapped),
    ("method.deprecatedEnum", ForeignMapping::Unmapped),
    ("method.deprecatedInterface", ForeignMapping::Unmapped),
    ("method.deprecatedTrait", ForeignMapping::Unmapped),
    ("method.dynamicName", ForeignMapping::Unmapped),
    ("method.finalPrivate", ForeignMapping::Unmapped),
    ("method.impossibleType", ForeignMapping::Unmapped),
    ("method.impure", ForeignMapping::Unmapped),
    (
        "method.impureOverridePureUnlessCallable",
        ForeignMapping::Unmapped,
    ),
    ("method.inVoidCast", ForeignMapping::Unmapped),
    ("method.internal", ForeignMapping::Unmapped),
    ("method.internalClass", ForeignMapping::Unmapped),
    ("method.internalEnum", ForeignMapping::Unmapped),
    ("method.internalInterface", ForeignMapping::Unmapped),
    ("method.internalTrait", ForeignMapping::Unmapped),
    ("method.missingOverride", ForeignMapping::Unmapped),
    ("method.nameCase", ForeignMapping::Unmapped),
    ("method.nonAbstract", ForeignMapping::Unmapped),
    // The two nonObject entries are the accepted over-suppression
    // direction: PHPStan reports any non-object receiver, CEL0034
    // only the possibly-null one, so the directive silences a
    // little more than it names. The static siblings
    // (staticMethod.nonObject, staticProperty.nonObject) stay
    // unmapped: CEL0034 is documented for method calls and property
    // accesses, not for static access, so mapping them would be
    // speculative.
    ("method.nonObject", ForeignMapping::Codes(&["CEL0034"])),
    ("method.nonStatic", ForeignMapping::Unmapped),
    ("method.notFound", ForeignMapping::Codes(&["CEL0030"])),
    ("method.override", ForeignMapping::Unmapped),
    ("method.parentMethodFinal", ForeignMapping::Unmapped),
    ("method.parentMethodFinalByPhpDoc", ForeignMapping::Unmapped),
    ("method.private", ForeignMapping::Unmapped),
    ("method.protected", ForeignMapping::Unmapped),
    ("method.resultDiscarded", ForeignMapping::Unmapped),
    ("method.resultUnused", ForeignMapping::Unmapped),
    ("method.shadowTemplate", ForeignMapping::Unmapped),
    ("method.static", ForeignMapping::Unmapped),
    ("method.staticCall", ForeignMapping::Unmapped),
    (
        "method.templateTypeNotInParameter",
        ForeignMapping::Unmapped,
    ),
    ("method.tentativeReturnType", ForeignMapping::Unmapped),
    ("method.unresolvableReturnType", ForeignMapping::Unmapped),
    ("method.unused", ForeignMapping::Unmapped),
    ("method.variance", ForeignMapping::Unmapped),
    ("method.visibility", ForeignMapping::Unmapped),
    ("method.void", ForeignMapping::Unmapped),
    ("methodTag.deprecatedClass", ForeignMapping::Unmapped),
    ("methodTag.deprecatedEnum", ForeignMapping::Unmapped),
    ("methodTag.deprecatedInterface", ForeignMapping::Unmapped),
    ("methodTag.deprecatedTrait", ForeignMapping::Unmapped),
    ("methodTag.internalClass", ForeignMapping::Unmapped),
    ("methodTag.internalEnum", ForeignMapping::Unmapped),
    ("methodTag.internalInterface", ForeignMapping::Unmapped),
    ("methodTag.internalTrait", ForeignMapping::Unmapped),
    ("methodTag.shadowTemplate", ForeignMapping::Unmapped),
    ("methodTag.trait", ForeignMapping::Unmapped),
    ("methodTag.unresolvableType", ForeignMapping::Unmapped),
    ("minus.leftNonNumeric", ForeignMapping::Unmapped),
    ("minus.rightNonNumeric", ForeignMapping::Unmapped),
    ("missingType.callable", ForeignMapping::Unmapped),
    ("missingType.checkedException", ForeignMapping::Unmapped),
    ("missingType.generics", ForeignMapping::Unmapped),
    ("missingType.iterableValue", ForeignMapping::Unmapped),
    ("missingType.parameter", ForeignMapping::Unmapped),
    ("missingType.property", ForeignMapping::Unmapped),
    ("missingType.return", ForeignMapping::Unmapped),
    ("mixin.deprecatedClass", ForeignMapping::Unmapped),
    ("mixin.deprecatedEnum", ForeignMapping::Unmapped),
    ("mixin.deprecatedInterface", ForeignMapping::Unmapped),
    ("mixin.deprecatedTrait", ForeignMapping::Unmapped),
    ("mixin.internalClass", ForeignMapping::Unmapped),
    ("mixin.internalEnum", ForeignMapping::Unmapped),
    ("mixin.internalInterface", ForeignMapping::Unmapped),
    ("mixin.internalTrait", ForeignMapping::Unmapped),
    ("mixin.nonObject", ForeignMapping::Unmapped),
    ("mixin.trait", ForeignMapping::Unmapped),
    ("mixin.unresolvableType", ForeignMapping::Unmapped),
    ("mod.leftNonNumeric", ForeignMapping::Unmapped),
    ("mod.rightNonNumeric", ForeignMapping::Unmapped),
    ("mul.leftNonNumeric", ForeignMapping::Unmapped),
    ("mul.rightNonNumeric", ForeignMapping::Unmapped),
    ("nette.rethrowException", ForeignMapping::Unmapped),
    ("new.abstract", ForeignMapping::Unmapped),
    ("new.dateInterval", ForeignMapping::Unmapped),
    ("new.dateTime", ForeignMapping::Unmapped),
    ("new.dateTimeImmutable", ForeignMapping::Unmapped),
    ("new.deprecatedClass", ForeignMapping::Unmapped),
    ("new.deprecatedEnum", ForeignMapping::Unmapped),
    ("new.deprecatedInterface", ForeignMapping::Unmapped),
    ("new.deprecatedTrait", ForeignMapping::Unmapped),
    ("new.enum", ForeignMapping::Unmapped),
    ("new.interface", ForeignMapping::Unmapped),
    ("new.internalClass", ForeignMapping::Unmapped),
    ("new.internalEnum", ForeignMapping::Unmapped),
    ("new.internalInterface", ForeignMapping::Unmapped),
    ("new.internalTrait", ForeignMapping::Unmapped),
    ("new.noConstructor", ForeignMapping::Unmapped),
    ("new.nonObject", ForeignMapping::Unmapped),
    ("new.privateConstructor", ForeignMapping::Unmapped),
    ("new.protectedConstructor", ForeignMapping::Unmapped),
    ("new.resultUnused", ForeignMapping::Unmapped),
    ("new.static", ForeignMapping::Unmapped),
    (
        "new.staticInAbstractClassStaticMethod",
        ForeignMapping::Unmapped,
    ),
    ("new.trait", ForeignMapping::Unmapped),
    ("new.unresolvableReturnType", ForeignMapping::Unmapped),
    ("new.void", ForeignMapping::Unmapped),
    ("notEqual.alwaysFalse", ForeignMapping::Unmapped),
    ("notEqual.alwaysTrue", ForeignMapping::Unmapped),
    ("notEqual.invalid", ForeignMapping::Unmapped),
    ("notEqual.notAllowed", ForeignMapping::Unmapped),
    ("notIdentical.alwaysFalse", ForeignMapping::Unmapped),
    ("notIdentical.alwaysTrue", ForeignMapping::Unmapped),
    ("nullCoalesce.expr", ForeignMapping::Unmapped),
    ("nullCoalesce.initializedProperty", ForeignMapping::Unmapped),
    ("nullCoalesce.offset", ForeignMapping::Unmapped),
    ("nullCoalesce.property", ForeignMapping::Unmapped),
    ("nullCoalesce.unnecessary", ForeignMapping::Unmapped),
    ("nullCoalesce.variable", ForeignMapping::Unmapped),
    ("nullableType.mixed", ForeignMapping::Unmapped),
    ("nullableType.never", ForeignMapping::Unmapped),
    ("nullableType.void", ForeignMapping::Unmapped),
    ("nullsafe.assign", ForeignMapping::Unmapped),
    ("nullsafe.byRef", ForeignMapping::Unmapped),
    ("nullsafe.neverNull", ForeignMapping::Unmapped),
    ("offsetAccess.invalidOffset", ForeignMapping::Unmapped),
    ("offsetAccess.noDim", ForeignMapping::Unmapped),
    ("offsetAccess.nonArray", ForeignMapping::Unmapped),
    ("offsetAccess.nonOffsetAccessible", ForeignMapping::Unmapped),
    ("offsetAccess.notFound", ForeignMapping::Unmapped),
    ("offsetAssign.dimType", ForeignMapping::Unmapped),
    ("offsetAssign.valueType", ForeignMapping::Unmapped),
    ("outOfClass.parent", ForeignMapping::Unmapped),
    ("outOfClass.self", ForeignMapping::Unmapped),
    ("outOfClass.static", ForeignMapping::Unmapped),
    ("paramClosureThis.nonClosure", ForeignMapping::Unmapped),
    (
        "paramImmediatelyInvokedCallable.nonCallable",
        ForeignMapping::Unmapped,
    ),
    (
        "paramLaterInvokedCallable.nonCallable",
        ForeignMapping::Unmapped,
    ),
    ("paramOut.nestedUnusedType", ForeignMapping::Unmapped),
    ("paramOut.tooWideBool", ForeignMapping::Unmapped),
    ("paramOut.type", ForeignMapping::Unmapped),
    ("paramOut.unusedType", ForeignMapping::Unmapped),
    ("parameter.byRef", ForeignMapping::Unmapped),
    ("parameter.defaultValue", ForeignMapping::Unmapped),
    ("parameter.deprecatedClass", ForeignMapping::Unmapped),
    ("parameter.deprecatedEnum", ForeignMapping::Unmapped),
    ("parameter.deprecatedInterface", ForeignMapping::Unmapped),
    ("parameter.deprecatedTrait", ForeignMapping::Unmapped),
    ("parameter.duplicate", ForeignMapping::Unmapped),
    ("parameter.implicitlyNullable", ForeignMapping::Unmapped),
    ("parameter.internalClass", ForeignMapping::Unmapped),
    ("parameter.internalEnum", ForeignMapping::Unmapped),
    ("parameter.internalInterface", ForeignMapping::Unmapped),
    ("parameter.internalTrait", ForeignMapping::Unmapped),
    ("parameter.missing", ForeignMapping::Unmapped),
    ("parameter.noParent", ForeignMapping::Unmapped),
    ("parameter.notByRef", ForeignMapping::Unmapped),
    ("parameter.notFound", ForeignMapping::Unmapped),
    ("parameter.notOptional", ForeignMapping::Unmapped),
    ("parameter.notVariadic", ForeignMapping::Unmapped),
    ("parameter.phpDocType", ForeignMapping::Unmapped),
    ("parameter.requiredAfterOptional", ForeignMapping::Unmapped),
    ("parameter.superglobal", ForeignMapping::Unmapped),
    ("parameter.this", ForeignMapping::Unmapped),
    ("parameter.trait", ForeignMapping::Unmapped),
    ("parameter.unionTypeNotSupported", ForeignMapping::Unmapped),
    ("parameter.unresolvableNativeType", ForeignMapping::Unmapped),
    ("parameter.unresolvableType", ForeignMapping::Unmapped),
    ("parameter.variadic", ForeignMapping::Unmapped),
    ("parameter.variadicNotLast", ForeignMapping::Unmapped),
    ("parameterByRef.nestedUnusedType", ForeignMapping::Unmapped),
    ("parameterByRef.tooWideBool", ForeignMapping::Unmapped),
    ("parameterByRef.type", ForeignMapping::Unmapped),
    ("parameterByRef.unusedType", ForeignMapping::Unmapped),
    ("phpDoc.parseError", ForeignMapping::Unmapped),
    ("phpDoc.phpstanTag", ForeignMapping::Unmapped),
    ("phpParser.classRenamed", ForeignMapping::Unmapped),
    (
        "phpParser.nodeConnectingAttribute",
        ForeignMapping::Unmapped,
    ),
    ("phpstan.classNotFound", ForeignMapping::Unmapped),
    ("phpstan.debugScope", ForeignMapping::Unmapped),
    ("phpstan.dumpNativeType", ForeignMapping::Unmapped),
    ("phpstan.dumpPhpDocType", ForeignMapping::Unmapped),
    ("phpstan.dumpType", ForeignMapping::Unmapped),
    ("phpstan.internal", ForeignMapping::Unmapped),
    ("phpstan.nativeType", ForeignMapping::Unmapped),
    ("phpstan.parse", ForeignMapping::Unmapped),
    ("phpstan.path", ForeignMapping::Unmapped),
    ("phpstan.php", ForeignMapping::Unmapped),
    ("phpstan.reflection", ForeignMapping::Unmapped),
    ("phpstan.superType", ForeignMapping::Unmapped),
    ("phpstan.traitNotFound", ForeignMapping::Unmapped),
    ("phpstan.type", ForeignMapping::Unmapped),
    ("phpstan.unknownExpectation", ForeignMapping::Unmapped),
    ("phpstan.variable", ForeignMapping::Unmapped),
    ("phpstanApi.class", ForeignMapping::Unmapped),
    ("phpstanApi.classConstant", ForeignMapping::Unmapped),
    ("phpstanApi.constructor", ForeignMapping::Unmapped),
    ("phpstanApi.enum", ForeignMapping::Unmapped),
    ("phpstanApi.getTemplateType", ForeignMapping::Unmapped),
    ("phpstanApi.instanceofAssumption", ForeignMapping::Unmapped),
    ("phpstanApi.instanceofType", ForeignMapping::Unmapped),
    ("phpstanApi.interface", ForeignMapping::Unmapped),
    ("phpstanApi.method", ForeignMapping::Unmapped),
    ("phpstanApi.phpstanNamespace", ForeignMapping::Unmapped),
    ("phpstanApi.runtimeReflection", ForeignMapping::Unmapped),
    ("phpstanApi.trait", ForeignMapping::Unmapped),
    ("phpstanApi.varTagAssumption", ForeignMapping::Unmapped),
    (
        "phpstanPlayground.arrayDimFetchCast",
        ForeignMapping::Unmapped,
    ),
    ("phpstanPlayground.arrayKeyCast", ForeignMapping::Unmapped),
    (
        "phpstanPlayground.configParameter",
        ForeignMapping::Unmapped,
    ),
    ("phpstanPlayground.never", ForeignMapping::Unmapped),
    ("phpstanPlayground.noPhp", ForeignMapping::Unmapped),
    ("phpstanPlayground.phpDoc", ForeignMapping::Unmapped),
    (
        "phpstanPlayground.staticWithoutType",
        ForeignMapping::Unmapped,
    ),
    ("phpstanPlayground.traitUnused", ForeignMapping::Unmapped),
    ("phpunit.assertCount", ForeignMapping::Unmapped),
    ("phpunit.assertEquals", ForeignMapping::Unmapped),
    ("phpunit.assertFalse", ForeignMapping::Unmapped),
    ("phpunit.assertNull", ForeignMapping::Unmapped),
    ("phpunit.assertTrue", ForeignMapping::Unmapped),
    (
        "phpunit.attributeRequiresPhpVersion",
        ForeignMapping::Unmapped,
    ),
    ("phpunit.callParent", ForeignMapping::Unmapped),
    ("phpunit.covers", ForeignMapping::Unmapped),
    ("phpunit.coversClass", ForeignMapping::Unmapped),
    ("phpunit.coversDuplicate", ForeignMapping::Unmapped),
    ("phpunit.coversInterface", ForeignMapping::Unmapped),
    ("phpunit.coversMethod", ForeignMapping::Unmapped),
    ("phpunit.dataProviderClass", ForeignMapping::Unmapped),
    ("phpunit.dataProviderMethod", ForeignMapping::Unmapped),
    ("phpunit.dataProviderPublic", ForeignMapping::Unmapped),
    ("phpunit.dataProviderStatic", ForeignMapping::Unmapped),
    ("phpunit.invalidPhpDoc", ForeignMapping::Unmapped),
    ("phpunit.mockMethod", ForeignMapping::Unmapped),
    ("pipe.byRef", ForeignMapping::Unmapped),
    ("plus.leftNonNumeric", ForeignMapping::Unmapped),
    ("plus.rightNonNumeric", ForeignMapping::Unmapped),
    ("possiblyImpure.betweenPhpTags", ForeignMapping::Unmapped),
    ("possiblyImpure.die", ForeignMapping::Unmapped),
    ("possiblyImpure.echo", ForeignMapping::Unmapped),
    ("possiblyImpure.eval", ForeignMapping::Unmapped),
    ("possiblyImpure.exit", ForeignMapping::Unmapped),
    ("possiblyImpure.functionCall", ForeignMapping::Unmapped),
    ("possiblyImpure.global", ForeignMapping::Unmapped),
    ("possiblyImpure.include", ForeignMapping::Unmapped),
    ("possiblyImpure.methodCall", ForeignMapping::Unmapped),
    ("possiblyImpure.new", ForeignMapping::Unmapped),
    ("possiblyImpure.print", ForeignMapping::Unmapped),
    ("possiblyImpure.propertyAssign", ForeignMapping::Unmapped),
    (
        "possiblyImpure.propertyAssignByRef",
        ForeignMapping::Unmapped,
    ),
    ("possiblyImpure.propertyUnset", ForeignMapping::Unmapped),
    ("possiblyImpure.require", ForeignMapping::Unmapped),
    ("possiblyImpure.static", ForeignMapping::Unmapped),
    (
        "possiblyImpure.staticPropertyAccess",
        ForeignMapping::Unmapped,
    ),
    ("possiblyImpure.superglobal", ForeignMapping::Unmapped),
    ("possiblyImpure.yield", ForeignMapping::Unmapped),
    ("possiblyImpure.yieldFrom", ForeignMapping::Unmapped),
    ("postDec.expr", ForeignMapping::Unmapped),
    ("postDec.nonNumeric", ForeignMapping::Unmapped),
    ("postDec.type", ForeignMapping::Unmapped),
    ("postInc.expr", ForeignMapping::Unmapped),
    ("postInc.nonNumeric", ForeignMapping::Unmapped),
    ("postInc.type", ForeignMapping::Unmapped),
    ("pow.leftNonNumeric", ForeignMapping::Unmapped),
    ("pow.rightNonNumeric", ForeignMapping::Unmapped),
    ("preDec.expr", ForeignMapping::Unmapped),
    ("preDec.nonNumeric", ForeignMapping::Unmapped),
    ("preDec.type", ForeignMapping::Unmapped),
    ("preInc.expr", ForeignMapping::Unmapped),
    ("preInc.nonNumeric", ForeignMapping::Unmapped),
    ("preInc.type", ForeignMapping::Unmapped),
    ("print.nonString", ForeignMapping::Unmapped),
    ("property.abstract", ForeignMapping::Unmapped),
    ("property.abstractFinal", ForeignMapping::Unmapped),
    ("property.abstractFinalHook", ForeignMapping::Unmapped),
    ("property.abstractInInterface", ForeignMapping::Unmapped),
    ("property.abstractNonHooked", ForeignMapping::Unmapped),
    (
        "property.abstractOverridingNonAbstractHook",
        ForeignMapping::Unmapped,
    ),
    ("property.abstractPrivate", ForeignMapping::Unmapped),
    (
        "property.abstractWithoutAbstractHook",
        ForeignMapping::Unmapped,
    ),
    ("property.assignByRef", ForeignMapping::Unmapped),
    ("property.callableType", ForeignMapping::Unmapped),
    ("property.defaultValue", ForeignMapping::Unmapped),
    ("property.deprecated", ForeignMapping::Codes(&["CEL0023"])),
    ("property.deprecatedClass", ForeignMapping::Unmapped),
    ("property.deprecatedEnum", ForeignMapping::Unmapped),
    ("property.deprecatedInterface", ForeignMapping::Unmapped),
    ("property.deprecatedTrait", ForeignMapping::Unmapped),
    ("property.dynamicName", ForeignMapping::Unmapped),
    ("property.extraNativeType", ForeignMapping::Unmapped),
    ("property.final", ForeignMapping::Unmapped),
    ("property.finalInInterface", ForeignMapping::Unmapped),
    ("property.finalPrivate", ForeignMapping::Unmapped),
    ("property.finalPrivateHook", ForeignMapping::Unmapped),
    ("property.hookBodyInInterface", ForeignMapping::Unmapped),
    ("property.hookReadOnly", ForeignMapping::Unmapped),
    ("property.hookWithoutBody", ForeignMapping::Unmapped),
    ("property.hookedStatic", ForeignMapping::Unmapped),
    ("property.hooksNotSupported", ForeignMapping::Unmapped),
    ("property.inInterface", ForeignMapping::Unmapped),
    ("property.internal", ForeignMapping::Unmapped),
    ("property.internalClass", ForeignMapping::Unmapped),
    ("property.internalEnum", ForeignMapping::Unmapped),
    ("property.internalInterface", ForeignMapping::Unmapped),
    ("property.internalTrait", ForeignMapping::Unmapped),
    ("property.invalidPromoted", ForeignMapping::Unmapped),
    ("property.missingNativeType", ForeignMapping::Unmapped),
    ("property.missingOverride", ForeignMapping::Unmapped),
    ("property.nameNotString", ForeignMapping::Unmapped),
    ("property.nativeType", ForeignMapping::Unmapped),
    ("property.nestedUnusedType", ForeignMapping::Unmapped),
    ("property.neverRead", ForeignMapping::Unmapped),
    ("property.neverWritten", ForeignMapping::Unmapped),
    ("property.nonHookedInInterface", ForeignMapping::Unmapped),
    ("property.nonObject", ForeignMapping::Codes(&["CEL0034"])),
    ("property.nonPublicInInterface", ForeignMapping::Unmapped),
    ("property.nonStatic", ForeignMapping::Unmapped),
    ("property.notFound", ForeignMapping::Codes(&["CEL0031"])),
    ("property.notReadable", ForeignMapping::Unmapped),
    ("property.notWritable", ForeignMapping::Unmapped),
    ("property.onlyRead", ForeignMapping::Unmapped),
    ("property.onlyWritten", ForeignMapping::Unmapped),
    ("property.override", ForeignMapping::Unmapped),
    ("property.overrideAttribute", ForeignMapping::Unmapped),
    ("property.parentPropertyFinal", ForeignMapping::Unmapped),
    (
        "property.parentPropertyFinalByPhpDoc",
        ForeignMapping::Unmapped,
    ),
    ("property.phpDocType", ForeignMapping::Unmapped),
    ("property.private", ForeignMapping::Unmapped),
    ("property.promotedNotSupported", ForeignMapping::Unmapped),
    ("property.protected", ForeignMapping::Unmapped),
    ("property.readOnly", ForeignMapping::Unmapped),
    ("property.readOnlyAssignByRef", ForeignMapping::Unmapped),
    (
        "property.readOnlyAssignNotInConstructor",
        ForeignMapping::Unmapped,
    ),
    ("property.readOnlyAssignNotOnThis", ForeignMapping::Unmapped),
    (
        "property.readOnlyAssignOutOfClass",
        ForeignMapping::Unmapped,
    ),
    (
        "property.readOnlyByPhpDocAssignByRef",
        ForeignMapping::Unmapped,
    ),
    (
        "property.readOnlyByPhpDocAssignNotInConstructor",
        ForeignMapping::Unmapped,
    ),
    (
        "property.readOnlyByPhpDocAssignNotOnThis",
        ForeignMapping::Unmapped,
    ),
    (
        "property.readOnlyByPhpDocAssignOutOfClass",
        ForeignMapping::Unmapped,
    ),
    (
        "property.readOnlyByPhpDocDefaultValue",
        ForeignMapping::Unmapped,
    ),
    ("property.readOnlyDefaultValue", ForeignMapping::Unmapped),
    ("property.readOnlyInInterface", ForeignMapping::Unmapped),
    ("property.readOnlyNoNativeType", ForeignMapping::Unmapped),
    ("property.readOnlyNotSupported", ForeignMapping::Unmapped),
    ("property.readOnlyStatic", ForeignMapping::Unmapped),
    ("property.readWrite", ForeignMapping::Unmapped),
    ("property.static", ForeignMapping::Unmapped),
    ("property.staticAccess", ForeignMapping::Unmapped),
    (
        "property.staticAsymmetricVisibility",
        ForeignMapping::Unmapped,
    ),
    ("property.tooWideBool", ForeignMapping::Unmapped),
    ("property.trait", ForeignMapping::Unmapped),
    ("property.uninitialized", ForeignMapping::Unmapped),
    ("property.uninitializedReadonly", ForeignMapping::Unmapped),
    (
        "property.uninitializedReadonlyByPhpDoc",
        ForeignMapping::Unmapped,
    ),
    ("property.unresolvableNativeType", ForeignMapping::Unmapped),
    ("property.unresolvableType", ForeignMapping::Unmapped),
    ("property.unused", ForeignMapping::Unmapped),
    ("property.unusedType", ForeignMapping::Unmapped),
    ("property.virtualDefault", ForeignMapping::Unmapped),
    ("property.visibility", ForeignMapping::Unmapped),
    ("property.writeOnly", ForeignMapping::Unmapped),
    ("propertyGetHook.noRead", ForeignMapping::Unmapped),
    (
        "propertySetHook.nativeParameterType",
        ForeignMapping::Unmapped,
    ),
    ("propertySetHook.noAssign", ForeignMapping::Unmapped),
    ("propertySetHook.parameterType", ForeignMapping::Unmapped),
    ("propertyTag.deprecatedClass", ForeignMapping::Unmapped),
    ("propertyTag.deprecatedEnum", ForeignMapping::Unmapped),
    ("propertyTag.deprecatedInterface", ForeignMapping::Unmapped),
    ("propertyTag.deprecatedTrait", ForeignMapping::Unmapped),
    ("propertyTag.internalClass", ForeignMapping::Unmapped),
    ("propertyTag.internalEnum", ForeignMapping::Unmapped),
    ("propertyTag.internalInterface", ForeignMapping::Unmapped),
    ("propertyTag.internalTrait", ForeignMapping::Unmapped),
    ("propertyTag.trait", ForeignMapping::Unmapped),
    ("propertyTag.unresolvableType", ForeignMapping::Unmapped),
    ("pureFunction.parameterByRef", ForeignMapping::Unmapped),
    (
        "pureFunction.redundantUnlessCallable",
        ForeignMapping::Unmapped,
    ),
    ("pureFunction.void", ForeignMapping::Unmapped),
    ("pureMethod.parameterByRef", ForeignMapping::Unmapped),
    (
        "pureMethod.redundantUnlessCallable",
        ForeignMapping::Unmapped,
    ),
    ("pureMethod.void", ForeignMapping::Unmapped),
    ("regexp.pattern", ForeignMapping::Unmapped),
    ("require.fileNotFound", ForeignMapping::Unmapped),
    ("requireExtends.class", ForeignMapping::Unmapped),
    ("requireExtends.deprecatedClass", ForeignMapping::Unmapped),
    ("requireExtends.deprecatedEnum", ForeignMapping::Unmapped),
    (
        "requireExtends.deprecatedInterface",
        ForeignMapping::Unmapped,
    ),
    ("requireExtends.deprecatedTrait", ForeignMapping::Unmapped),
    ("requireExtends.duplicate", ForeignMapping::Unmapped),
    ("requireExtends.enum", ForeignMapping::Unmapped),
    ("requireExtends.finalClass", ForeignMapping::Unmapped),
    ("requireExtends.interface", ForeignMapping::Unmapped),
    ("requireExtends.internalClass", ForeignMapping::Unmapped),
    ("requireExtends.internalEnum", ForeignMapping::Unmapped),
    ("requireExtends.internalInterface", ForeignMapping::Unmapped),
    ("requireExtends.internalTrait", ForeignMapping::Unmapped),
    ("requireExtends.nonObject", ForeignMapping::Unmapped),
    ("requireExtends.onClass", ForeignMapping::Unmapped),
    ("requireExtends.onEnum", ForeignMapping::Unmapped),
    ("requireExtends.onInterface", ForeignMapping::Unmapped),
    ("requireExtends.onTrait", ForeignMapping::Unmapped),
    ("requireExtends.trait", ForeignMapping::Unmapped),
    ("requireImplements.class", ForeignMapping::Unmapped),
    (
        "requireImplements.deprecatedClass",
        ForeignMapping::Unmapped,
    ),
    ("requireImplements.deprecatedEnum", ForeignMapping::Unmapped),
    (
        "requireImplements.deprecatedInterface",
        ForeignMapping::Unmapped,
    ),
    (
        "requireImplements.deprecatedTrait",
        ForeignMapping::Unmapped,
    ),
    ("requireImplements.enum", ForeignMapping::Unmapped),
    ("requireImplements.interface", ForeignMapping::Unmapped),
    ("requireImplements.internalClass", ForeignMapping::Unmapped),
    ("requireImplements.internalEnum", ForeignMapping::Unmapped),
    (
        "requireImplements.internalInterface",
        ForeignMapping::Unmapped,
    ),
    ("requireImplements.internalTrait", ForeignMapping::Unmapped),
    ("requireImplements.nonObject", ForeignMapping::Unmapped),
    ("requireImplements.onClass", ForeignMapping::Unmapped),
    ("requireImplements.onEnum", ForeignMapping::Unmapped),
    ("requireImplements.onInterface", ForeignMapping::Unmapped),
    ("requireImplements.onTrait", ForeignMapping::Unmapped),
    ("requireImplements.trait", ForeignMapping::Unmapped),
    ("requireOnce.fileNotFound", ForeignMapping::Unmapped),
    ("return.deprecatedClass", ForeignMapping::Unmapped),
    ("return.deprecatedEnum", ForeignMapping::Unmapped),
    ("return.deprecatedInterface", ForeignMapping::Unmapped),
    ("return.deprecatedTrait", ForeignMapping::Unmapped),
    ("return.empty", ForeignMapping::Unmapped),
    ("return.internalClass", ForeignMapping::Unmapped),
    ("return.internalEnum", ForeignMapping::Unmapped),
    ("return.internalInterface", ForeignMapping::Unmapped),
    ("return.internalTrait", ForeignMapping::Unmapped),
    ("return.missing", ForeignMapping::Unmapped),
    ("return.nestedUnusedType", ForeignMapping::Unmapped),
    ("return.never", ForeignMapping::Unmapped),
    ("return.neverTypeNotSupported", ForeignMapping::Unmapped),
    ("return.noParent", ForeignMapping::Unmapped),
    ("return.phpDocType", ForeignMapping::Unmapped),
    ("return.tooWideBool", ForeignMapping::Unmapped),
    ("return.trait", ForeignMapping::Unmapped),
    ("return.type", ForeignMapping::Unmapped),
    ("return.unionTypeNotSupported", ForeignMapping::Unmapped),
    ("return.unresolvableNativeType", ForeignMapping::Unmapped),
    ("return.unresolvableType", ForeignMapping::Unmapped),
    ("return.unusedType", ForeignMapping::Unmapped),
    ("return.void", ForeignMapping::Unmapped),
    ("sealed.deprecatedClass", ForeignMapping::Unmapped),
    ("sealed.deprecatedEnum", ForeignMapping::Unmapped),
    ("sealed.deprecatedInterface", ForeignMapping::Unmapped),
    ("sealed.deprecatedTrait", ForeignMapping::Unmapped),
    ("sealed.internalClass", ForeignMapping::Unmapped),
    ("sealed.internalEnum", ForeignMapping::Unmapped),
    ("sealed.internalInterface", ForeignMapping::Unmapped),
    ("sealed.internalTrait", ForeignMapping::Unmapped),
    ("sealed.nonObject", ForeignMapping::Unmapped),
    ("sealed.onEnum", ForeignMapping::Unmapped),
    ("sealed.onTrait", ForeignMapping::Unmapped),
    ("selfOut.deprecatedClass", ForeignMapping::Unmapped),
    ("selfOut.deprecatedEnum", ForeignMapping::Unmapped),
    ("selfOut.deprecatedInterface", ForeignMapping::Unmapped),
    ("selfOut.deprecatedTrait", ForeignMapping::Unmapped),
    ("selfOut.internalClass", ForeignMapping::Unmapped),
    ("selfOut.internalEnum", ForeignMapping::Unmapped),
    ("selfOut.internalInterface", ForeignMapping::Unmapped),
    ("selfOut.internalTrait", ForeignMapping::Unmapped),
    ("selfOut.static", ForeignMapping::Unmapped),
    ("selfOut.trait", ForeignMapping::Unmapped),
    ("selfOut.type", ForeignMapping::Unmapped),
    ("selfOut.unresolvableType", ForeignMapping::Unmapped),
    ("smaller.alwaysFalse", ForeignMapping::Unmapped),
    ("smaller.alwaysTrue", ForeignMapping::Unmapped),
    ("smaller.invalid", ForeignMapping::Unmapped),
    ("smallerOrEqual.alwaysFalse", ForeignMapping::Unmapped),
    ("smallerOrEqual.alwaysTrue", ForeignMapping::Unmapped),
    ("smallerOrEqual.invalid", ForeignMapping::Unmapped),
    ("spaceship.invalid", ForeignMapping::Unmapped),
    ("static.this", ForeignMapping::Unmapped),
    (
        "staticClassAccess.privateConstant",
        ForeignMapping::Unmapped,
    ),
    ("staticClassAccess.privateMethod", ForeignMapping::Unmapped),
    (
        "staticClassAccess.privateProperty",
        ForeignMapping::Unmapped,
    ),
    ("staticMethod.alreadyNarrowedType", ForeignMapping::Unmapped),
    ("staticMethod.callToAbstract", ForeignMapping::Unmapped),
    (
        "staticMethod.deprecated",
        ForeignMapping::Codes(&["CEL0023"]),
    ),
    ("staticMethod.deprecatedClass", ForeignMapping::Unmapped),
    ("staticMethod.deprecatedEnum", ForeignMapping::Unmapped),
    ("staticMethod.deprecatedInterface", ForeignMapping::Unmapped),
    ("staticMethod.deprecatedTrait", ForeignMapping::Unmapped),
    ("staticMethod.dynamicCall", ForeignMapping::Unmapped),
    ("staticMethod.dynamicName", ForeignMapping::Unmapped),
    ("staticMethod.impossibleType", ForeignMapping::Unmapped),
    ("staticMethod.inVoidCast", ForeignMapping::Unmapped),
    ("staticMethod.internal", ForeignMapping::Unmapped),
    ("staticMethod.internalClass", ForeignMapping::Unmapped),
    ("staticMethod.internalEnum", ForeignMapping::Unmapped),
    ("staticMethod.internalInterface", ForeignMapping::Unmapped),
    ("staticMethod.internalTrait", ForeignMapping::Unmapped),
    ("staticMethod.nameCase", ForeignMapping::Unmapped),
    ("staticMethod.nonObject", ForeignMapping::Unmapped),
    ("staticMethod.notFound", ForeignMapping::Codes(&["CEL0030"])),
    ("staticMethod.private", ForeignMapping::Unmapped),
    ("staticMethod.protected", ForeignMapping::Unmapped),
    ("staticMethod.resultDiscarded", ForeignMapping::Unmapped),
    ("staticMethod.resultUnused", ForeignMapping::Unmapped),
    (
        "staticMethod.unresolvableReturnType",
        ForeignMapping::Unmapped,
    ),
    ("staticMethod.void", ForeignMapping::Unmapped),
    // Not seeded by the plan, added here: the exact static sibling
    // of property.deprecated, and CEL0023 is "symbol deprecated"
    // for every symbol kind. Upstream reads "Accessed static
    // property is marked as deprecated."
    (
        "staticProperty.deprecated",
        ForeignMapping::Codes(&["CEL0023"]),
    ),
    ("staticProperty.deprecatedClass", ForeignMapping::Unmapped),
    ("staticProperty.deprecatedEnum", ForeignMapping::Unmapped),
    (
        "staticProperty.deprecatedInterface",
        ForeignMapping::Unmapped,
    ),
    ("staticProperty.deprecatedTrait", ForeignMapping::Unmapped),
    ("staticProperty.dynamicName", ForeignMapping::Unmapped),
    ("staticProperty.internal", ForeignMapping::Unmapped),
    ("staticProperty.internalClass", ForeignMapping::Unmapped),
    ("staticProperty.internalEnum", ForeignMapping::Unmapped),
    ("staticProperty.internalInterface", ForeignMapping::Unmapped),
    ("staticProperty.internalTrait", ForeignMapping::Unmapped),
    ("staticProperty.nonObject", ForeignMapping::Unmapped),
    ("staticProperty.nonStaticAccess", ForeignMapping::Unmapped),
    (
        "staticProperty.notFound",
        ForeignMapping::Codes(&["CEL0031"]),
    ),
    ("staticProperty.private", ForeignMapping::Unmapped),
    ("staticProperty.protected", ForeignMapping::Unmapped),
    ("switch.type", ForeignMapping::Unmapped),
    ("symfonyConsole.argumentNotFound", ForeignMapping::Unmapped),
    ("symfonyConsole.optionNotFound", ForeignMapping::Unmapped),
    ("symfonyContainer.privateService", ForeignMapping::Unmapped),
    ("symfonyContainer.serviceNotFound", ForeignMapping::Unmapped),
    ("ternary.alwaysFalse", ForeignMapping::Unmapped),
    ("ternary.alwaysTrue", ForeignMapping::Unmapped),
    ("ternary.condNotBoolean", ForeignMapping::Unmapped),
    ("ternary.resultUnused", ForeignMapping::Unmapped),
    ("ternary.shortNotAllowed", ForeignMapping::Unmapped),
    ("throw.notSupported", ForeignMapping::Unmapped),
    ("throw.notThrowable", ForeignMapping::Unmapped),
    ("throws.notCovariant", ForeignMapping::Unmapped),
    (
        "throws.notCovariantWithImplicitVoid",
        ForeignMapping::Unmapped,
    ),
    ("throws.notThrowable", ForeignMapping::Unmapped),
    ("throws.shouldBeVoid", ForeignMapping::Unmapped),
    ("throws.unusedType", ForeignMapping::Unmapped),
    ("throws.void", ForeignMapping::Unmapped),
    ("trait.allowDynamicProperties", ForeignMapping::Unmapped),
    ("trait.deprecatedAttribute", ForeignMapping::Unmapped),
    ("trait.disallowedSubtype", ForeignMapping::Unmapped),
    ("trait.duplicate", ForeignMapping::Unmapped),
    ("trait.duplicateConstant", ForeignMapping::Unmapped),
    ("trait.duplicateEnumCase", ForeignMapping::Unmapped),
    ("trait.duplicateMethod", ForeignMapping::Unmapped),
    ("trait.duplicateProperty", ForeignMapping::Unmapped),
    ("trait.nameCase", ForeignMapping::Unmapped),
    ("trait.nameInUse", ForeignMapping::Unmapped),
    ("trait.notFound", ForeignMapping::Unmapped),
    ("trait.unused", ForeignMapping::Unmapped),
    ("traitUse.class", ForeignMapping::Unmapped),
    ("traitUse.deprecatedClass", ForeignMapping::Unmapped),
    ("traitUse.deprecatedEnum", ForeignMapping::Unmapped),
    ("traitUse.deprecatedInterface", ForeignMapping::Unmapped),
    ("traitUse.deprecatedTrait", ForeignMapping::Unmapped),
    ("traitUse.enum", ForeignMapping::Unmapped),
    ("traitUse.interface", ForeignMapping::Unmapped),
    ("traitUse.internalClass", ForeignMapping::Unmapped),
    ("traitUse.internalEnum", ForeignMapping::Unmapped),
    ("traitUse.internalInterface", ForeignMapping::Unmapped),
    ("traitUse.internalTrait", ForeignMapping::Unmapped),
    ("typeAlias.circular", ForeignMapping::Unmapped),
    ("typeAlias.deprecatedClass", ForeignMapping::Unmapped),
    ("typeAlias.deprecatedEnum", ForeignMapping::Unmapped),
    ("typeAlias.deprecatedInterface", ForeignMapping::Unmapped),
    ("typeAlias.deprecatedTrait", ForeignMapping::Unmapped),
    ("typeAlias.duplicate", ForeignMapping::Unmapped),
    ("typeAlias.internalClass", ForeignMapping::Unmapped),
    ("typeAlias.internalEnum", ForeignMapping::Unmapped),
    ("typeAlias.internalInterface", ForeignMapping::Unmapped),
    ("typeAlias.internalTrait", ForeignMapping::Unmapped),
    ("typeAlias.invalidName", ForeignMapping::Unmapped),
    ("typeAlias.invalidType", ForeignMapping::Unmapped),
    ("typeAlias.notFound", ForeignMapping::Unmapped),
    ("typeAlias.trait", ForeignMapping::Unmapped),
    ("typeAlias.unresolvableType", ForeignMapping::Unmapped),
    ("unaryMinus.nonNumeric", ForeignMapping::Unmapped),
    ("unaryOp.invalid", ForeignMapping::Unmapped),
    ("unaryPlus.nonNumeric", ForeignMapping::Unmapped),
    ("unionType.mixed", ForeignMapping::Unmapped),
    ("unionType.never", ForeignMapping::Unmapped),
    ("unionType.void", ForeignMapping::Unmapped),
    ("unset.hookedProperty", ForeignMapping::Unmapped),
    ("unset.offset", ForeignMapping::Unmapped),
    ("unset.possiblyHookedProperty", ForeignMapping::Unmapped),
    ("unset.readOnlyProperty", ForeignMapping::Unmapped),
    ("unset.readOnlyPropertyByPhpDoc", ForeignMapping::Unmapped),
    ("unset.variable", ForeignMapping::Unmapped),
    ("use.nameInUse", ForeignMapping::Unmapped),
    ("varTag.deprecatedClass", ForeignMapping::Unmapped),
    ("varTag.deprecatedEnum", ForeignMapping::Unmapped),
    ("varTag.deprecatedInterface", ForeignMapping::Unmapped),
    ("varTag.deprecatedTrait", ForeignMapping::Unmapped),
    ("varTag.differentVariable", ForeignMapping::Unmapped),
    ("varTag.internalClass", ForeignMapping::Unmapped),
    ("varTag.internalEnum", ForeignMapping::Unmapped),
    ("varTag.internalInterface", ForeignMapping::Unmapped),
    ("varTag.internalTrait", ForeignMapping::Unmapped),
    ("varTag.misplaced", ForeignMapping::Unmapped),
    ("varTag.multipleTags", ForeignMapping::Unmapped),
    ("varTag.nativeType", ForeignMapping::Unmapped),
    ("varTag.noVariable", ForeignMapping::Unmapped),
    ("varTag.trait", ForeignMapping::Unmapped),
    ("varTag.type", ForeignMapping::Unmapped),
    ("varTag.unresolvableType", ForeignMapping::Unmapped),
    ("varTag.variableNotFound", ForeignMapping::Unmapped),
    ("variable.dynamicName", ForeignMapping::Unmapped),
    ("variable.implicitArray", ForeignMapping::Unmapped),
    ("variable.undefined", ForeignMapping::Unmapped),
    ("void.pure", ForeignMapping::Unmapped),
    ("while.alwaysFalse", ForeignMapping::Unmapped),
    ("while.alwaysTrue", ForeignMapping::Unmapped),
    ("while.condNotBoolean", ForeignMapping::Unmapped),
    ("whitespace.bom", ForeignMapping::Unmapped),
    ("whitespace.fileEnd", ForeignMapping::Unmapped),
];

// Psalm's Possibly* prefix marks a finding the tool is unsure of,
// not a different finding class, so PossiblyInvalidArgument and
// PossiblyUndefinedMethod share their certain siblings' codes.
const PSALM: &[(&str, ForeignMapping)] = &[
    ("AbstractInstantiation", ForeignMapping::Unmapped),
    ("AbstractMethodCall", ForeignMapping::Unmapped),
    ("AmbiguousConstantInheritance", ForeignMapping::Unmapped),
    ("ArgumentTypeCoercion", ForeignMapping::Unmapped),
    ("AssignmentToVoid", ForeignMapping::Unmapped),
    ("CheckType", ForeignMapping::Unmapped),
    ("CircularReference", ForeignMapping::Unmapped),
    ("ClassMustBeFinal", ForeignMapping::Unmapped),
    ("ComplexFunction", ForeignMapping::Unmapped),
    ("ComplexMethod", ForeignMapping::Unmapped),
    ("ConfigIssue", ForeignMapping::Unmapped),
    ("ConflictingReferenceConstraint", ForeignMapping::Unmapped),
    ("ConstantDeclarationInTrait", ForeignMapping::Unmapped),
    ("ConstructorSignatureMismatch", ForeignMapping::Unmapped),
    ("ContinueOutsideLoop", ForeignMapping::Unmapped),
    ("DeprecatedClass", ForeignMapping::Codes(&["CEL0023"])),
    ("DeprecatedConstant", ForeignMapping::Codes(&["CEL0023"])),
    ("DeprecatedFunction", ForeignMapping::Codes(&["CEL0023"])),
    ("DeprecatedInterface", ForeignMapping::Unmapped),
    ("DeprecatedMethod", ForeignMapping::Codes(&["CEL0023"])),
    ("DeprecatedProperty", ForeignMapping::Codes(&["CEL0023"])),
    ("DeprecatedTrait", ForeignMapping::Unmapped),
    ("DirectConstructorCall", ForeignMapping::Unmapped),
    ("DocblockTypeContradiction", ForeignMapping::Unmapped),
    ("DuplicateArrayKey", ForeignMapping::Unmapped),
    ("DuplicateClass", ForeignMapping::Unmapped),
    ("DuplicateConstant", ForeignMapping::Unmapped),
    ("DuplicateEnumCase", ForeignMapping::Unmapped),
    ("DuplicateEnumCaseValue", ForeignMapping::Unmapped),
    ("DuplicateFunction", ForeignMapping::Unmapped),
    ("DuplicateMethod", ForeignMapping::Unmapped),
    ("DuplicateParam", ForeignMapping::Unmapped),
    ("DuplicateProperty", ForeignMapping::Unmapped),
    ("EmptyArrayAccess", ForeignMapping::Unmapped),
    ("ExtensionRequirementViolation", ForeignMapping::Unmapped),
    ("FalsableReturnStatement", ForeignMapping::Unmapped),
    ("FalseOperand", ForeignMapping::Unmapped),
    ("ForbiddenCode", ForeignMapping::Unmapped),
    ("IfThisIsMismatch", ForeignMapping::Unmapped),
    (
        "ImplementationRequirementViolation",
        ForeignMapping::Unmapped,
    ),
    ("ImplementedParamTypeMismatch", ForeignMapping::Unmapped),
    ("ImplementedReturnTypeMismatch", ForeignMapping::Unmapped),
    ("ImplicitToStringCast", ForeignMapping::Unmapped),
    ("ImpureByReferenceAssignment", ForeignMapping::Unmapped),
    ("ImpureFunctionCall", ForeignMapping::Unmapped),
    ("ImpureMethodCall", ForeignMapping::Unmapped),
    ("ImpurePropertyAssignment", ForeignMapping::Unmapped),
    ("ImpurePropertyFetch", ForeignMapping::Unmapped),
    ("ImpureStaticProperty", ForeignMapping::Unmapped),
    ("ImpureStaticVariable", ForeignMapping::Unmapped),
    ("ImpureVariable", ForeignMapping::Unmapped),
    ("InaccessibleClassConstant", ForeignMapping::Unmapped),
    ("InaccessibleMethod", ForeignMapping::Unmapped),
    ("InaccessibleProperty", ForeignMapping::Unmapped),
    ("InheritorViolation", ForeignMapping::Unmapped),
    ("InterfaceInstantiation", ForeignMapping::Unmapped),
    ("InternalClass", ForeignMapping::Unmapped),
    ("InternalMethod", ForeignMapping::Unmapped),
    ("InternalProperty", ForeignMapping::Unmapped),
    ("InvalidArgument", ForeignMapping::Codes(&["CEL0035"])),
    ("InvalidArrayAccess", ForeignMapping::Unmapped),
    ("InvalidArrayAssignment", ForeignMapping::Unmapped),
    ("InvalidArrayOffset", ForeignMapping::Unmapped),
    ("InvalidAttribute", ForeignMapping::Unmapped),
    ("InvalidCast", ForeignMapping::Unmapped),
    ("InvalidCatch", ForeignMapping::Unmapped),
    ("InvalidClass", ForeignMapping::Unmapped),
    ("InvalidClassConstantType", ForeignMapping::Unmapped),
    ("InvalidClone", ForeignMapping::Unmapped),
    ("InvalidConstantAssignmentValue", ForeignMapping::Unmapped),
    ("InvalidDocblock", ForeignMapping::Unmapped),
    ("InvalidDocblockParamName", ForeignMapping::Unmapped),
    ("InvalidEnumBackingType", ForeignMapping::Unmapped),
    ("InvalidEnumCaseValue", ForeignMapping::Unmapped),
    ("InvalidEnumMethod", ForeignMapping::Unmapped),
    ("InvalidExtendClass", ForeignMapping::Unmapped),
    ("InvalidFalsableReturnType", ForeignMapping::Unmapped),
    ("InvalidFunctionCall", ForeignMapping::Unmapped),
    ("InvalidGlobal", ForeignMapping::Unmapped),
    ("InvalidInterfaceImplementation", ForeignMapping::Unmapped),
    ("InvalidIterator", ForeignMapping::Unmapped),
    ("InvalidLiteralArgument", ForeignMapping::Unmapped),
    ("InvalidMethodCall", ForeignMapping::Unmapped),
    ("InvalidNamedArgument", ForeignMapping::Codes(&["CEL0038"])),
    ("InvalidNullableReturnType", ForeignMapping::Unmapped),
    ("InvalidOperand", ForeignMapping::Unmapped),
    ("InvalidOverride", ForeignMapping::Unmapped),
    ("InvalidParamDefault", ForeignMapping::Unmapped),
    ("InvalidParent", ForeignMapping::Unmapped),
    ("InvalidPassByReference", ForeignMapping::Unmapped),
    ("InvalidPropertyAssignment", ForeignMapping::Unmapped),
    ("InvalidPropertyAssignmentValue", ForeignMapping::Unmapped),
    ("InvalidPropertyFetch", ForeignMapping::Unmapped),
    ("InvalidReturnStatement", ForeignMapping::Unmapped),
    ("InvalidReturnType", ForeignMapping::Unmapped),
    ("InvalidScalarArgument", ForeignMapping::Unmapped),
    ("InvalidScope", ForeignMapping::Unmapped),
    ("InvalidStaticInvocation", ForeignMapping::Unmapped),
    ("InvalidStringClass", ForeignMapping::Unmapped),
    ("InvalidTemplateParam", ForeignMapping::Unmapped),
    ("InvalidThrow", ForeignMapping::Unmapped),
    ("InvalidToString", ForeignMapping::Unmapped),
    ("InvalidTraversableImplementation", ForeignMapping::Unmapped),
    ("InvalidTypeImport", ForeignMapping::Unmapped),
    ("LessSpecificClassConstantType", ForeignMapping::Unmapped),
    (
        "LessSpecificImplementedReturnType",
        ForeignMapping::Unmapped,
    ),
    ("LessSpecificReturnStatement", ForeignMapping::Unmapped),
    ("LessSpecificReturnType", ForeignMapping::Unmapped),
    ("LiteralKeyUnshapedArray", ForeignMapping::Unmapped),
    ("LoopInvalidation", ForeignMapping::Unmapped),
    ("MethodSignatureMismatch", ForeignMapping::Unmapped),
    (
        "MethodSignatureMustOmitReturnType",
        ForeignMapping::Unmapped,
    ),
    (
        "MethodSignatureMustProvideReturnType",
        ForeignMapping::Unmapped,
    ),
    ("MismatchingDocblockParamType", ForeignMapping::Unmapped),
    ("MismatchingDocblockPropertyType", ForeignMapping::Unmapped),
    ("MismatchingDocblockReturnType", ForeignMapping::Unmapped),
    ("MissingClassConstType", ForeignMapping::Unmapped),
    ("MissingClosureParamType", ForeignMapping::Unmapped),
    ("MissingClosureReturnType", ForeignMapping::Unmapped),
    ("MissingConstructor", ForeignMapping::Unmapped),
    ("MissingDependency", ForeignMapping::Unmapped),
    ("MissingDocblockType", ForeignMapping::Unmapped),
    ("MissingFile", ForeignMapping::Unmapped),
    ("MissingImmutableAnnotation", ForeignMapping::Unmapped),
    ("MissingOverrideAttribute", ForeignMapping::Unmapped),
    ("MissingParamType", ForeignMapping::Unmapped),
    ("MissingPropertyType", ForeignMapping::Unmapped),
    ("MissingReturnType", ForeignMapping::Unmapped),
    ("MissingTemplateParam", ForeignMapping::Unmapped),
    ("MissingThrowsDocblock", ForeignMapping::Unmapped),
    ("MixedArgument", ForeignMapping::Unmapped),
    ("MixedArgumentTypeCoercion", ForeignMapping::Unmapped),
    ("MixedArrayAccess", ForeignMapping::Unmapped),
    ("MixedArrayAssignment", ForeignMapping::Unmapped),
    ("MixedArrayOffset", ForeignMapping::Unmapped),
    ("MixedArrayTypeCoercion", ForeignMapping::Unmapped),
    ("MixedAssignment", ForeignMapping::Unmapped),
    ("MixedClone", ForeignMapping::Unmapped),
    ("MixedFunctionCall", ForeignMapping::Unmapped),
    ("MixedMethodCall", ForeignMapping::Unmapped),
    ("MixedOperand", ForeignMapping::Unmapped),
    ("MixedPropertyAssignment", ForeignMapping::Unmapped),
    ("MixedPropertyFetch", ForeignMapping::Unmapped),
    ("MixedPropertyTypeCoercion", ForeignMapping::Unmapped),
    ("MixedReturnStatement", ForeignMapping::Unmapped),
    ("MixedReturnTypeCoercion", ForeignMapping::Unmapped),
    ("MixedStringOffsetAssignment", ForeignMapping::Unmapped),
    ("MoreSpecificImplementedParamType", ForeignMapping::Unmapped),
    ("MoreSpecificReturnType", ForeignMapping::Unmapped),
    ("MutableDependency", ForeignMapping::Unmapped),
    ("NamedArgumentNotAllowed", ForeignMapping::Unmapped),
    ("NoEnumProperties", ForeignMapping::Unmapped),
    ("NoInterfaceProperties", ForeignMapping::Unmapped),
    ("NoValue", ForeignMapping::Unmapped),
    ("NonInvariantDocblockPropertyType", ForeignMapping::Unmapped),
    ("NonInvariantPropertyType", ForeignMapping::Unmapped),
    ("NonStaticSelfCall", ForeignMapping::Unmapped),
    ("NonVariableReferenceReturn", ForeignMapping::Unmapped),
    ("NullArgument", ForeignMapping::Unmapped),
    ("NullArrayAccess", ForeignMapping::Unmapped),
    ("NullArrayOffset", ForeignMapping::Unmapped),
    ("NullFunctionCall", ForeignMapping::Unmapped),
    ("NullIterator", ForeignMapping::Unmapped),
    ("NullOperand", ForeignMapping::Unmapped),
    ("NullPropertyAssignment", ForeignMapping::Unmapped),
    ("NullPropertyFetch", ForeignMapping::Unmapped),
    ("NullReference", ForeignMapping::Unmapped),
    ("NullableReturnStatement", ForeignMapping::Unmapped),
    ("OverriddenFinalConstant", ForeignMapping::Unmapped),
    ("OverriddenInterfaceConstant", ForeignMapping::Unmapped),
    ("OverriddenMethodAccess", ForeignMapping::Unmapped),
    ("OverriddenPropertyAccess", ForeignMapping::Unmapped),
    ("ParadoxicalCondition", ForeignMapping::Unmapped),
    ("ParamNameMismatch", ForeignMapping::Unmapped),
    ("ParentNotFound", ForeignMapping::Unmapped),
    ("PluginIssue", ForeignMapping::Unmapped),
    ("PossibleRawObjectIteration", ForeignMapping::Unmapped),
    ("PossiblyFalseArgument", ForeignMapping::Unmapped),
    ("PossiblyFalseIterator", ForeignMapping::Unmapped),
    ("PossiblyFalseOperand", ForeignMapping::Unmapped),
    (
        "PossiblyFalsePropertyAssignmentValue",
        ForeignMapping::Unmapped,
    ),
    ("PossiblyFalseReference", ForeignMapping::Unmapped),
    (
        "PossiblyInvalidArgument",
        ForeignMapping::Codes(&["CEL0035"]),
    ),
    ("PossiblyInvalidArrayAccess", ForeignMapping::Unmapped),
    ("PossiblyInvalidArrayAssignment", ForeignMapping::Unmapped),
    ("PossiblyInvalidArrayOffset", ForeignMapping::Unmapped),
    ("PossiblyInvalidCast", ForeignMapping::Unmapped),
    ("PossiblyInvalidClone", ForeignMapping::Unmapped),
    ("PossiblyInvalidDocblockTag", ForeignMapping::Unmapped),
    ("PossiblyInvalidFunctionCall", ForeignMapping::Unmapped),
    ("PossiblyInvalidIterator", ForeignMapping::Unmapped),
    ("PossiblyInvalidMethodCall", ForeignMapping::Unmapped),
    ("PossiblyInvalidOperand", ForeignMapping::Unmapped),
    (
        "PossiblyInvalidPropertyAssignment",
        ForeignMapping::Unmapped,
    ),
    (
        "PossiblyInvalidPropertyAssignmentValue",
        ForeignMapping::Unmapped,
    ),
    ("PossiblyInvalidPropertyFetch", ForeignMapping::Unmapped),
    ("PossiblyNullArgument", ForeignMapping::Unmapped),
    ("PossiblyNullArrayAccess", ForeignMapping::Unmapped),
    ("PossiblyNullArrayAssignment", ForeignMapping::Unmapped),
    ("PossiblyNullArrayOffset", ForeignMapping::Unmapped),
    ("PossiblyNullFunctionCall", ForeignMapping::Unmapped),
    ("PossiblyNullIterator", ForeignMapping::Unmapped),
    ("PossiblyNullOperand", ForeignMapping::Unmapped),
    ("PossiblyNullPropertyAssignment", ForeignMapping::Unmapped),
    (
        "PossiblyNullPropertyAssignmentValue",
        ForeignMapping::Unmapped,
    ),
    (
        "PossiblyNullPropertyFetch",
        ForeignMapping::Codes(&["CEL0034"]),
    ),
    ("PossiblyNullReference", ForeignMapping::Codes(&["CEL0034"])),
    ("PossiblyUndefinedArrayOffset", ForeignMapping::Unmapped),
    ("PossiblyUndefinedGlobalVariable", ForeignMapping::Unmapped),
    ("PossiblyUndefinedIntArrayOffset", ForeignMapping::Unmapped),
    (
        "PossiblyUndefinedMethod",
        ForeignMapping::Codes(&["CEL0030"]),
    ),
    (
        "PossiblyUndefinedStringArrayOffset",
        ForeignMapping::Unmapped,
    ),
    ("PossiblyUndefinedVariable", ForeignMapping::Unmapped),
    ("PossiblyUnusedMethod", ForeignMapping::Unmapped),
    ("PossiblyUnusedParam", ForeignMapping::Unmapped),
    ("PossiblyUnusedProperty", ForeignMapping::Unmapped),
    ("PossiblyUnusedReturnValue", ForeignMapping::Unmapped),
    ("PrivateFinalMethod", ForeignMapping::Unmapped),
    ("PropertyNotSetInConstructor", ForeignMapping::Unmapped),
    ("PropertyTypeCoercion", ForeignMapping::Unmapped),
    ("RawObjectIteration", ForeignMapping::Unmapped),
    ("RedundantCast", ForeignMapping::Unmapped),
    ("RedundantCastGivenDocblockType", ForeignMapping::Unmapped),
    ("RedundantCondition", ForeignMapping::Unmapped),
    (
        "RedundantConditionGivenDocblockType",
        ForeignMapping::Unmapped,
    ),
    ("RedundantFlag", ForeignMapping::Unmapped),
    ("RedundantFunctionCall", ForeignMapping::Unmapped),
    (
        "RedundantFunctionCallGivenDocblockType",
        ForeignMapping::Unmapped,
    ),
    ("RedundantIdentityWithTrue", ForeignMapping::Unmapped),
    (
        "RedundantPropertyInitializationCheck",
        ForeignMapping::Unmapped,
    ),
    ("ReferenceConstraintViolation", ForeignMapping::Unmapped),
    (
        "ReferenceReusedFromConfusingScope",
        ForeignMapping::Unmapped,
    ),
    ("ReservedWord", ForeignMapping::Unmapped),
    ("RiskyCast", ForeignMapping::Unmapped),
    ("RiskyTruthyFalsyComparison", ForeignMapping::Unmapped),
    ("StringIncrement", ForeignMapping::Unmapped),
    ("TaintedCallable", ForeignMapping::Unmapped),
    ("TaintedCookie", ForeignMapping::Unmapped),
    ("TaintedCustom", ForeignMapping::Unmapped),
    ("TaintedEval", ForeignMapping::Unmapped),
    ("TaintedExtract", ForeignMapping::Unmapped),
    ("TaintedFile", ForeignMapping::Unmapped),
    ("TaintedHeader", ForeignMapping::Unmapped),
    ("TaintedHtml", ForeignMapping::Unmapped),
    ("TaintedInclude", ForeignMapping::Unmapped),
    ("TaintedInput", ForeignMapping::Unmapped),
    ("TaintedLdap", ForeignMapping::Unmapped),
    ("TaintedSSRF", ForeignMapping::Unmapped),
    ("TaintedShell", ForeignMapping::Unmapped),
    ("TaintedSleep", ForeignMapping::Unmapped),
    ("TaintedSql", ForeignMapping::Unmapped),
    ("TaintedSystemSecret", ForeignMapping::Unmapped),
    ("TaintedTextWithQuotes", ForeignMapping::Unmapped),
    ("TaintedUnserialize", ForeignMapping::Unmapped),
    ("TaintedUserSecret", ForeignMapping::Unmapped),
    ("TaintedXpath", ForeignMapping::Unmapped),
    ("TooFewArguments", ForeignMapping::Codes(&["CEL0036"])),
    ("TooManyArguments", ForeignMapping::Codes(&["CEL0037"])),
    ("TooManyTemplateParams", ForeignMapping::Unmapped),
    ("Trace", ForeignMapping::Unmapped),
    ("TraitMethodSignatureMismatch", ForeignMapping::Unmapped),
    ("TypeDoesNotContainNull", ForeignMapping::Unmapped),
    ("TypeDoesNotContainType", ForeignMapping::Unmapped),
    ("UncaughtThrowInGlobalScope", ForeignMapping::Unmapped),
    ("UndefinedAttributeClass", ForeignMapping::Unmapped),
    // Psalm folds two different resolution outcomes into one
    // "undefined" identifier. CEL0018/CEL0019/CEL0020 fire when a
    // reference resolves nowhere at all, in the project, its Composer
    // dependencies, or the bundled stubs. CEL0021 and CEL0022 fire on
    // a different outcome: the reference does resolve through the
    // stubs, but its availability window falls outside the project's
    // configured PHP version range (CEL0021 when the symbol is not
    // yet available at the minimum version, CEL0022 when it was
    // already removed by the maximum version). Psalm has no separate
    // identifier for that version-window case, so `UndefinedClass`,
    // `UndefinedConstant`, and `UndefinedFunction` below must each
    // widen to all three codes. Narrowing to only the undefined-symbol
    // code would under-suppress: `@psalm-suppress UndefinedFunction`
    // written over a call Celerrate reports as CEL0022 would see the
    // diagnostic reappear once the directive is matched against a
    // single narrower code, and under-suppression is the one failure
    // direction this project treats as a defect. Do not shrink these
    // back to one code.
    //
    // `UndefinedConstant` carries a second fold on top of the
    // version-window one: Psalm has no separate identifier for an
    // undefined class constant, so it reports both an undefined global
    // constant and an undefined class constant (CEL0032) under this
    // same name. The vendored catalogue has no `UndefinedClassConstant`
    // entry, so `UndefinedConstant` is the only identifier a Psalm user
    // can write over a missing class constant. The entry must therefore
    // cover CEL0032 as well; shrinking it back would under-suppress.
    (
        "UndefinedClass",
        ForeignMapping::Codes(&["CEL0018", "CEL0021", "CEL0022"]),
    ),
    (
        "UndefinedConstant",
        ForeignMapping::Codes(&["CEL0020", "CEL0021", "CEL0022", "CEL0032"]),
    ),
    ("UndefinedDocblockClass", ForeignMapping::Unmapped),
    (
        "UndefinedFunction",
        ForeignMapping::Codes(&["CEL0019", "CEL0021", "CEL0022"]),
    ),
    ("UndefinedGlobalVariable", ForeignMapping::Unmapped),
    ("UndefinedInterface", ForeignMapping::Unmapped),
    ("UndefinedInterfaceMethod", ForeignMapping::Unmapped),
    ("UndefinedMagicMethod", ForeignMapping::Codes(&["CEL0030"])),
    ("UndefinedMagicPropertyAssignment", ForeignMapping::Unmapped),
    (
        "UndefinedMagicPropertyFetch",
        ForeignMapping::Codes(&["CEL0031"]),
    ),
    ("UndefinedMethod", ForeignMapping::Codes(&["CEL0030"])),
    ("UndefinedPropertyAssignment", ForeignMapping::Unmapped),
    (
        "UndefinedPropertyFetch",
        ForeignMapping::Codes(&["CEL0031"]),
    ),
    ("UndefinedThisPropertyAssignment", ForeignMapping::Unmapped),
    (
        "UndefinedThisPropertyFetch",
        ForeignMapping::Codes(&["CEL0031"]),
    ),
    ("UndefinedTrace", ForeignMapping::Unmapped),
    ("UndefinedTrait", ForeignMapping::Unmapped),
    ("UndefinedVariable", ForeignMapping::Unmapped),
    ("UnevaluatedCode", ForeignMapping::Unmapped),
    ("UnhandledMatchCondition", ForeignMapping::Unmapped),
    ("UnimplementedAbstractMethod", ForeignMapping::Unmapped),
    ("UnimplementedInterfaceMethod", ForeignMapping::Unmapped),
    ("UninitializedProperty", ForeignMapping::Unmapped),
    ("UnnecessaryVarAnnotation", ForeignMapping::Unmapped),
    ("UnrecognizedExpression", ForeignMapping::Unmapped),
    ("UnrecognizedStatement", ForeignMapping::Unmapped),
    ("UnresolvableConstant", ForeignMapping::Unmapped),
    ("UnresolvableInclude", ForeignMapping::Unmapped),
    ("UnsafeGenericInstantiation", ForeignMapping::Unmapped),
    ("UnsafeInstantiation", ForeignMapping::Unmapped),
    (
        "UnsupportedPropertyReferenceUsage",
        ForeignMapping::Unmapped,
    ),
    ("UnsupportedReferenceUsage", ForeignMapping::Unmapped),
    ("UnusedBaselineEntry", ForeignMapping::Unmapped),
    ("UnusedClass", ForeignMapping::Unmapped),
    ("UnusedClosureParam", ForeignMapping::Unmapped),
    ("UnusedConstructor", ForeignMapping::Unmapped),
    ("UnusedDocblockParam", ForeignMapping::Unmapped),
    ("UnusedForeachValue", ForeignMapping::Unmapped),
    ("UnusedFunctionCall", ForeignMapping::Unmapped),
    ("UnusedIssueHandlerSuppression", ForeignMapping::Unmapped),
    ("UnusedMethod", ForeignMapping::Unmapped),
    ("UnusedMethodCall", ForeignMapping::Unmapped),
    ("UnusedParam", ForeignMapping::Unmapped),
    ("UnusedProperty", ForeignMapping::Unmapped),
    ("UnusedPsalmSuppress", ForeignMapping::Unmapped),
    ("UnusedReturnValue", ForeignMapping::Unmapped),
    ("UnusedVariable", ForeignMapping::Unmapped),
    ("all", ForeignMapping::ScopeWide),
];

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::indexing_slicing)]

    use super::*;

    #[test]
    fn both_tables_are_sorted_and_unique() {
        for dialect in [Dialect::Phpstan, Dialect::Psalm] {
            let entries = correspondence_entries(dialect);
            for pair in entries.windows(2) {
                assert!(
                    pair[0].0 < pair[1].0,
                    "{dialect:?}: {} must sort strictly before {}",
                    pair[0].0,
                    pair[1].0,
                );
            }
        }
    }

    #[test]
    fn lookup_is_exact_case_and_a_miss_is_unmapped() {
        assert_ne!(
            foreign_mapping(Dialect::Psalm, "UndefinedClass"),
            ForeignMapping::Unmapped,
        );
        assert_eq!(
            foreign_mapping(Dialect::Psalm, "undefinedclass"),
            ForeignMapping::Unmapped,
        );
        assert_eq!(
            foreign_mapping(Dialect::Phpstan, "no.suchIdentifier"),
            ForeignMapping::Unmapped,
        );
    }

    #[test]
    fn psalm_all_is_an_explicit_scope_wide_entry() {
        assert_eq!(
            foreign_mapping(Dialect::Psalm, "all"),
            ForeignMapping::ScopeWide,
        );
    }

    #[test]
    fn the_multi_code_example_of_the_design_holds() {
        // PHPStan's single arguments.count covers findings that span
        // several CEL codes (design section 8).
        assert_eq!(
            foreign_mapping(Dialect::Phpstan, "arguments.count"),
            ForeignMapping::Codes(&["CEL0036", "CEL0037"]),
        );
    }

    #[test]
    fn no_codes_entry_is_empty() {
        for dialect in [Dialect::Phpstan, Dialect::Psalm] {
            for (identifier, mapping) in correspondence_entries(dialect) {
                if let ForeignMapping::Codes(codes) = mapping {
                    assert!(!codes.is_empty(), "{identifier} maps to an empty set");
                }
            }
        }
    }
}
