//! Generated by `cargo xtask codegen`; do not edit by hand.
//! Token kinds come from xtask's token table, node kinds from
//! `php.ungram` (`ErrorNode` appended by the generator).

/// Every kind of token and node in PHP syntax.
///
/// One vocabulary shared by the whole syntax layer, `#[repr(u16)]`
/// so the rowan tree stores it directly. Token kinds first, node
/// kinds after them.
///
/// Keywords each get their own kind, resolved case-insensitively by
/// the lexer. Semi-reserved uses (`$object->list()`, `const FOR = 1;`,
/// `enum` as a plain name) are the parser's business: it re-treats
/// keyword kinds as identifiers where the grammar allows. `true`,
/// `false`, `null`, `self`, `parent`, and the magic constants are
/// plain identifiers, resolved semantically.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(u16)]
pub enum SyntaxKind {
    Whitespace,
    /// `//` and `#` comments, up to the end of the line or a `?>`.
    LineComment,
    /// `/* ... */` comments.
    BlockComment,
    /// `/** ... */` docblocks, a distinct kind: the type engine reads them.
    DocComment,
    /// A `#!` first line.
    Shebang,
    /// `<?php`.
    OpenTag,
    /// `<?=`.
    OpenTagEcho,
    /// `<?`, lexed unconditionally; availability is a semantic judgment.
    ShortOpenTag,
    /// `?>`, plus the single newline PHP swallows after it, if present.
    CloseTag,
    /// Everything outside PHP tags.
    InlineHtml,
    Identifier,
    /// `$name`.
    Variable,
    IntegerLiteral,
    FloatLiteral,
    /// A whole `'...'` (or `b'...'`) string, quotes included.
    SingleQuotedString,
    /// A literal run inside an interpolated string, heredoc, or backtick.
    StringFragment,
    /// A `"` delimiter (or the opening `b"`).
    DoubleQuote,
    /// A `` ` `` delimiter.
    Backtick,
    /// `<<<LABEL` (or quoted label), trailing newline included.
    HeredocStart,
    /// The closing label of a heredoc or nowdoc, indentation included.
    HeredocEnd,
    /// `${` opening the deprecated interpolation form.
    DollarOpenBrace,
    Abstract,
    And,
    Array,
    As,
    Break,
    Callable,
    Case,
    Catch,
    Class,
    Clone,
    Const,
    Continue,
    Declare,
    Default,
    Do,
    Echo,
    Else,
    ElseIf,
    Empty,
    EndDeclare,
    EndFor,
    EndForeach,
    EndIf,
    EndSwitch,
    EndWhile,
    Enum,
    Eval,
    /// `exit` and its alias `die`.
    Exit,
    Extends,
    Final,
    Finally,
    Fn,
    For,
    Foreach,
    Function,
    Global,
    Goto,
    If,
    Implements,
    Include,
    IncludeOnce,
    InstanceOf,
    InsteadOf,
    Interface,
    Isset,
    List,
    Match,
    Namespace,
    New,
    Or,
    Print,
    Private,
    Protected,
    Public,
    Readonly,
    Require,
    RequireOnce,
    Return,
    Static,
    Switch,
    Throw,
    Trait,
    Try,
    Unset,
    Use,
    Var,
    While,
    Xor,
    Yield,
    /// `yield from`, one token as in Zend, interior whitespace included.
    YieldFrom,
    IntCast,
    BoolCast,
    FloatCast,
    StringCast,
    BinaryCast,
    ArrayCast,
    ObjectCast,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    StarStar,
    Equals,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    DotEquals,
    PercentEquals,
    StarStarEquals,
    AmpersandEquals,
    PipeEquals,
    CaretEquals,
    LessLessEquals,
    GreaterGreaterEquals,
    QuestionQuestionEquals,
    EqualsEquals,
    EqualsEqualsEquals,
    /// `!=` and its alias `<>`.
    BangEquals,
    BangEqualsEquals,
    Less,
    Greater,
    LessEquals,
    GreaterEquals,
    /// `<=>`.
    Spaceship,
    PlusPlus,
    MinusMinus,
    LessLess,
    GreaterGreater,
    Dot,
    Bang,
    AmpersandAmpersand,
    PipePipe,
    QuestionQuestion,
    Question,
    Colon,
    ColonColon,
    Semicolon,
    Comma,
    Ampersand,
    Pipe,
    /// `|>`, the PHP 8.5 pipe operator.
    PipeGreater,
    Caret,
    Tilde,
    At,
    Dollar,
    Backslash,
    /// `->`.
    Arrow,
    /// `?->`.
    NullsafeArrow,
    /// `=>`.
    FatArrow,
    /// `...`.
    Ellipsis,
    OpenParenthesis,
    CloseParenthesis,
    OpenBracket,
    CloseBracket,
    OpenBrace,
    CloseBrace,
    /// `#[`, distinct from the `#` line comment.
    AttributeOpen,
    /// A character no rule accepts.
    Error,
    // Node kinds, owned by php.ungram.
    /// A literal expression: integer, float, or single-quoted string.
    Literal,
    /// A `$variable` used as an expression.
    VariableReference,
    /// `$$name` and `${expression}`.
    DynamicVariableExpression,
    /// `( expression )`.
    ParenthesizedExpression,
    /// One binary operation: left operand, operator token, right operand.
    /// The operator token distinguishes `+` from `instanceof` from `|>`.
    BinaryExpression,
    /// A prefix operation: `!`, `~`, unary `+`/`-`, `@`, `++`, `--`.
    PrefixExpression,
    /// A postfix operation: `++`, `--`.
    PostfixExpression,
    /// A cast: the single cast token, then the operand.
    CastExpression,
    /// `condition ? middle : third`; the short form `?:` has no middle, so
    /// position cannot assign roles and the accessors are hand-written.
    TernaryExpression,
    /// `target = value` and the compound forms; `= &value` keeps its
    /// ampersand as a token child. Whether the target is assignable is
    /// a semantic judgment.
    AssignmentExpression,
    /// A name used as an expression: a constant fetch or a callee. Also
    /// `static` as a scoped-access subject, a bare keyword token with no
    /// Name child.
    NameExpression,
    /// A call: the callee expression, then its argument list.
    CallExpression,
    /// `subject->name` and `subject?->name`.
    MemberAccessExpression,
    /// `subject::name`: constants, methods, static properties, `::class`.
    ScopedAccessExpression,
    /// `subject[index]`; the index is absent in the push form `$a[]`.
    IndexExpression,
    /// `[ elements ]` or `array( elements )`; also the destructuring
    /// target shape. Empty destructuring slots keep their commas as
    /// direct children.
    ArrayExpression,
    /// `list( elements )`, the keyword destructuring form.
    ListExpression,
    /// `"..."` with fragments and interpolations.
    InterpolatedString,
    /// A heredoc or nowdoc, start to end label.
    HeredocExpression,
    /// A backtick string: shell execution.
    ShellExecExpression,
    /// `new` with a class reference and optional constructor arguments.
    /// The reference is one of: a Name (`new Foo(1)`), the bare `static`
    /// keyword, a variable or parenthesized expression, or an anonymous
    /// ClassDeclaration (whose own constructor arguments sit inside it).
    NewExpression,
    /// `clone value` or the 8.5 function form `clone(...)`.
    CloneExpression,
    /// `isset( arguments )`.
    IssetExpression,
    /// `empty( argument )`.
    EmptyExpression,
    /// `eval( argument )`.
    EvalExpression,
    /// `exit` / `die`, with an optional argument list since 8.4.
    ExitExpression,
    /// `print operand`.
    PrintExpression,
    /// `throw operand`, an expression since PHP 8.0.
    ThrowExpression,
    /// `yield`, `yield value`, `yield key => value`, `yield from source`.
    /// `yield $v` puts the value first while `yield $k => $v` puts the key
    /// first, so the accessors are hand-written.
    YieldExpression,
    /// `include`, `include_once`, `require`, `require_once`; the
    /// keyword token distinguishes them.
    IncludeExpression,
    /// `match ( subject ) { arms }`.
    MatchExpression,
    /// `function (...) use (...) { ... }`, optionally `static`, with an
    /// optional by-reference `&` and return type.
    ClosureExpression,
    /// `fn (...) => expression`, optionally `static`.
    ArrowFunctionExpression,
    /// `{ statements }`.
    Block,
    /// A lone `;`.
    EmptyStatement,
    /// `echo expression, expression;`.
    EchoStatement,
    /// An expression used as a statement, terminator included.
    ExpressionStatement,
    /// `return;` or `return expression;`.
    ReturnStatement,
    /// `break;` or `break level;`; level validity is semantic.
    BreakStatement,
    /// `continue;` or `continue level;`; level validity is semantic.
    ContinueStatement,
    /// `global $a, $b;`.
    GlobalStatement,
    /// `static $a = 1, $b;`, the function-static declaration.
    StaticStatement,
    /// `unset( targets );`.
    UnsetStatement,
    /// `goto label;`; whether the label exists is semantic.
    GotoStatement,
    /// `label:`, the target of a `goto`.
    LabelStatement,
    /// `if (condition) body`, with optional `ElseIfClause`s and one
    /// optional `ElseClause`, in either classic or alternative syntax. The
    /// classic body is a single statement child; the alternative body is
    /// the statement list before the clauses.
    IfStatement,
    /// `while (condition) body`, either syntax.
    WhileStatement,
    /// `do body while (condition);`.
    DoWhileStatement,
    /// `for (initializers; condition; updates) body`, either syntax.
    ForStatement,
    /// `foreach (subject as key => value) body`, either syntax; the
    /// `=>` separates the optional key target from the value target, so
    /// position alone cannot assign roles and the accessors are
    /// hand-written.
    ForeachStatement,
    /// `switch (subject) { cases }`, either syntax.
    SwitchStatement,
    /// `try block`, then catch clauses and an optional finally.
    TryStatement,
    /// `declare( directives ) body`, either syntax; the body may be a
    /// lone `;` (an empty statement). A classic body of `?>` leaves a bare
    /// CloseTag token with no statement-node child, so the statement
    /// accessor yields nothing there.
    DeclareStatement,
    /// `function name(parameters): type { body }`, the top-level form;
    /// methods arrive with the declarations plan.
    FunctionDeclaration,
    /// `const FOO = 1, BAR = 2;`, optionally typed (8.3), at the top
    /// level or as a class member (with modifiers).
    ConstantDeclaration,
    /// `namespace A\B;` or `namespace A\B { ... }` or `namespace { ... }`.
    NamespaceDeclaration,
    /// `use A\B;` and every import shape: aliases, `function`/`const`
    /// types, clause lists, group imports.
    UseDeclaration,
    /// `class Name extends B implements C, D { members }`, with
    /// optional `abstract` / `final` / `readonly` modifiers. Anonymous
    /// classes (`new class(...) { ... }`) share this kind and simply
    /// have no name; their constructor arguments sit before the
    /// heritage clauses. The name is semi-reserved (`class List {}`
    /// parses), so its accessor is hand-written.
    ClassDeclaration,
    /// `interface Name extends A, B { members }`. The name is
    /// semi-reserved, so its accessor is hand-written.
    InterfaceDeclaration,
    /// `trait Name { members }`. Heritage clauses parse permissively on
    /// traits; their legality is semantic. The name is semi-reserved, so
    /// its accessor is hand-written.
    TraitDeclaration,
    /// `enum Name: BackingType implements A { cases and members }`.
    EnumDeclaration,
    /// One named type: a qualified `Name`, or a keyword type token
    /// (`array`, `callable`, `static`, and permissively any keyword)
    /// sitting bare. One concept in two shapes; the hand-written
    /// `name_or_keyword()` extension unifies them.
    NamedType,
    /// `?type`.
    NullableType,
    /// `A|B|C`, one flat node for the whole chain.
    UnionType,
    /// `A&B&C`, one flat node for the whole chain.
    IntersectionType,
    /// `( type )` inside a type: the DNF grouping form.
    ParenthesizedType,
    /// `public int $a = 1, $b;`: modifiers, optional type, then the
    /// declarator elements.
    PropertyDeclaration,
    /// `function name(parameters): type { body }` (or `;` for the
    /// abstract and interface forms) as a class member, modifiers
    /// included. The name is semi-reserved (`public function list()`), so
    /// its accessor is hand-written.
    MethodDeclaration,
    /// `use TraitA, TraitB;` inside a class body, with an optional
    /// adaptation list instead of the semicolon.
    TraitUseClause,
    /// `case Name;` or `case Name = expression;`. Case names are
    /// semi-reserved, so the accessor is hand-written.
    EnumCase,
    /// `$name`, `$name->property`, `$name[offset]` inside a string.
    SimpleInterpolation,
    /// `{ expression }` inside a string.
    BraceInterpolation,
    /// `${ ... }` inside a string, the deprecated form.
    DollarBraceInterpolation,
    /// `A::member insteadof B, C;`. The reference name, the semi-reserved
    /// member, and the excluded names share types, so the accessors are
    /// hand-written.
    TraitPrecedence,
    /// `[A::]member as [visibility] [name];`. The member and the alias are
    /// semi-reserved and position-dependent, so the accessors are
    /// hand-written.
    TraitAlias,
    /// The root node: one parsed PHP file. Open and close tags and inline
    /// HTML sit between the statements as bare tokens.
    SourceFile,
    /// A possibly-qualified name: `Foo`, `Foo\Bar`, `\Foo`, `namespace\Foo`.
    Name,
    /// `( argument, ... )`, including the lone `...` of a first-class
    /// callable, which sits directly in the list.
    ArgumentList,
    /// One argument: optional `label:`, optional `...`, optional `&`,
    /// then the expression. The label is semi-reserved (any keyword), so
    /// its accessor is hand-written.
    Argument,
    /// The name after `->`, `?->`, or `::`: identifier, any keyword
    /// (semi-reserved, hand-written accessor), variable, or
    /// `{ expression }`.
    MemberName,
    /// One element: optional `...`, optional `&`, expression, then
    /// optionally `=>` (optional `&`) expression. `[value]` and
    /// `[key => value]` put a different role at the first position, so the
    /// accessors are hand-written.
    ArrayElement,
    /// One arm: a condition list (or `default`), `=>`, the body. The body
    /// is the expression after the arrow; position alone cannot separate
    /// it from the conditions, so the accessors are hand-written.
    MatchArm,
    /// `#[Attribute(arguments), Other]`: one bracketed group.
    AttributeGroup,
    /// `( parameter, ... )`.
    ParameterList,
    /// `use ( variables )` on a closure.
    ClosureUseClause,
    /// One parameter: optional type, `&`, `...`, the variable, and an
    /// optional default. Constructor promotion admits the full member
    /// modifier set; which modifiers are legal here is semantic.
    Parameter,
    /// `{ get; set(...) { ... } }` on a property or a promoted
    /// parameter (8.4).
    PropertyHookList,
    /// One declared static: the variable and its optional initializer.
    StaticVariable,
    /// `elseif (condition) body` (or its alternative-syntax form).
    ElseIfClause,
    /// `else body` (or its alternative-syntax form).
    ElseClause,
    /// One of `for`'s three sections: a possibly-empty comma-separated
    /// expression list, always present as a node so the sections stay
    /// addressable by position.
    ForExpressionList,
    /// One `case expression:` or `default:` section, its statements
    /// included; the body ends where the next section (or the switch)
    /// begins, so an empty body is a fallthrough.
    SwitchCase,
    /// `catch (Type | Type $variable) block`; the variable is optional
    /// since PHP 8.0.
    CatchClause,
    /// `finally block`.
    FinallyClause,
    /// One `name = value` directive; which names and values are legal
    /// is semantic.
    DeclareDirective,
    /// One `name = value` element of a constant declaration. The name is
    /// semi-reserved (`const FOR = 1;`), so its accessor is hand-written.
    ConstantElement,
    /// One imported name: optional per-item `function`/`const` type
    /// (inside groups), the name, an optional group or alias. The alias is
    /// semi-reserved, so its accessor is hand-written.
    UseClause,
    /// `\{ items }` of a grouped import.
    UseGroup,
    /// `extends` and its comma-separated names.
    ExtendsClause,
    /// `implements` and its comma-separated names.
    ImplementsClause,
    /// `{ members }` of a class-like body.
    MemberList,
    /// One `$name [= initializer]` element; a hooked property carries
    /// its `PropertyHookList` here.
    PropertyElement,
    /// `{ adaptations }` of a trait use.
    TraitAdaptationList,
    /// One hook: optional `final`, optional `&`, the name, an optional
    /// parameter list, then `;`, `=> expression;`, or a block. Hook names
    /// are semi-reserved in practice, so the accessor is hand-written.
    PropertyHook,
    /// One attribute inside a group: a name and optional arguments.
    Attribute,
    /// Recovery wreckage: tokens no grammar rule accepted.
    ErrorNode,
}

impl SyntaxKind {
    /// Every kind, in declaration (and therefore discriminant) order.
    const ALL: &[SyntaxKind] = &[
        SyntaxKind::Whitespace,
        SyntaxKind::LineComment,
        SyntaxKind::BlockComment,
        SyntaxKind::DocComment,
        SyntaxKind::Shebang,
        SyntaxKind::OpenTag,
        SyntaxKind::OpenTagEcho,
        SyntaxKind::ShortOpenTag,
        SyntaxKind::CloseTag,
        SyntaxKind::InlineHtml,
        SyntaxKind::Identifier,
        SyntaxKind::Variable,
        SyntaxKind::IntegerLiteral,
        SyntaxKind::FloatLiteral,
        SyntaxKind::SingleQuotedString,
        SyntaxKind::StringFragment,
        SyntaxKind::DoubleQuote,
        SyntaxKind::Backtick,
        SyntaxKind::HeredocStart,
        SyntaxKind::HeredocEnd,
        SyntaxKind::DollarOpenBrace,
        SyntaxKind::Abstract,
        SyntaxKind::And,
        SyntaxKind::Array,
        SyntaxKind::As,
        SyntaxKind::Break,
        SyntaxKind::Callable,
        SyntaxKind::Case,
        SyntaxKind::Catch,
        SyntaxKind::Class,
        SyntaxKind::Clone,
        SyntaxKind::Const,
        SyntaxKind::Continue,
        SyntaxKind::Declare,
        SyntaxKind::Default,
        SyntaxKind::Do,
        SyntaxKind::Echo,
        SyntaxKind::Else,
        SyntaxKind::ElseIf,
        SyntaxKind::Empty,
        SyntaxKind::EndDeclare,
        SyntaxKind::EndFor,
        SyntaxKind::EndForeach,
        SyntaxKind::EndIf,
        SyntaxKind::EndSwitch,
        SyntaxKind::EndWhile,
        SyntaxKind::Enum,
        SyntaxKind::Eval,
        SyntaxKind::Exit,
        SyntaxKind::Extends,
        SyntaxKind::Final,
        SyntaxKind::Finally,
        SyntaxKind::Fn,
        SyntaxKind::For,
        SyntaxKind::Foreach,
        SyntaxKind::Function,
        SyntaxKind::Global,
        SyntaxKind::Goto,
        SyntaxKind::If,
        SyntaxKind::Implements,
        SyntaxKind::Include,
        SyntaxKind::IncludeOnce,
        SyntaxKind::InstanceOf,
        SyntaxKind::InsteadOf,
        SyntaxKind::Interface,
        SyntaxKind::Isset,
        SyntaxKind::List,
        SyntaxKind::Match,
        SyntaxKind::Namespace,
        SyntaxKind::New,
        SyntaxKind::Or,
        SyntaxKind::Print,
        SyntaxKind::Private,
        SyntaxKind::Protected,
        SyntaxKind::Public,
        SyntaxKind::Readonly,
        SyntaxKind::Require,
        SyntaxKind::RequireOnce,
        SyntaxKind::Return,
        SyntaxKind::Static,
        SyntaxKind::Switch,
        SyntaxKind::Throw,
        SyntaxKind::Trait,
        SyntaxKind::Try,
        SyntaxKind::Unset,
        SyntaxKind::Use,
        SyntaxKind::Var,
        SyntaxKind::While,
        SyntaxKind::Xor,
        SyntaxKind::Yield,
        SyntaxKind::YieldFrom,
        SyntaxKind::IntCast,
        SyntaxKind::BoolCast,
        SyntaxKind::FloatCast,
        SyntaxKind::StringCast,
        SyntaxKind::BinaryCast,
        SyntaxKind::ArrayCast,
        SyntaxKind::ObjectCast,
        SyntaxKind::Plus,
        SyntaxKind::Minus,
        SyntaxKind::Star,
        SyntaxKind::Slash,
        SyntaxKind::Percent,
        SyntaxKind::StarStar,
        SyntaxKind::Equals,
        SyntaxKind::PlusEquals,
        SyntaxKind::MinusEquals,
        SyntaxKind::StarEquals,
        SyntaxKind::SlashEquals,
        SyntaxKind::DotEquals,
        SyntaxKind::PercentEquals,
        SyntaxKind::StarStarEquals,
        SyntaxKind::AmpersandEquals,
        SyntaxKind::PipeEquals,
        SyntaxKind::CaretEquals,
        SyntaxKind::LessLessEquals,
        SyntaxKind::GreaterGreaterEquals,
        SyntaxKind::QuestionQuestionEquals,
        SyntaxKind::EqualsEquals,
        SyntaxKind::EqualsEqualsEquals,
        SyntaxKind::BangEquals,
        SyntaxKind::BangEqualsEquals,
        SyntaxKind::Less,
        SyntaxKind::Greater,
        SyntaxKind::LessEquals,
        SyntaxKind::GreaterEquals,
        SyntaxKind::Spaceship,
        SyntaxKind::PlusPlus,
        SyntaxKind::MinusMinus,
        SyntaxKind::LessLess,
        SyntaxKind::GreaterGreater,
        SyntaxKind::Dot,
        SyntaxKind::Bang,
        SyntaxKind::AmpersandAmpersand,
        SyntaxKind::PipePipe,
        SyntaxKind::QuestionQuestion,
        SyntaxKind::Question,
        SyntaxKind::Colon,
        SyntaxKind::ColonColon,
        SyntaxKind::Semicolon,
        SyntaxKind::Comma,
        SyntaxKind::Ampersand,
        SyntaxKind::Pipe,
        SyntaxKind::PipeGreater,
        SyntaxKind::Caret,
        SyntaxKind::Tilde,
        SyntaxKind::At,
        SyntaxKind::Dollar,
        SyntaxKind::Backslash,
        SyntaxKind::Arrow,
        SyntaxKind::NullsafeArrow,
        SyntaxKind::FatArrow,
        SyntaxKind::Ellipsis,
        SyntaxKind::OpenParenthesis,
        SyntaxKind::CloseParenthesis,
        SyntaxKind::OpenBracket,
        SyntaxKind::CloseBracket,
        SyntaxKind::OpenBrace,
        SyntaxKind::CloseBrace,
        SyntaxKind::AttributeOpen,
        SyntaxKind::Error,
        SyntaxKind::Literal,
        SyntaxKind::VariableReference,
        SyntaxKind::DynamicVariableExpression,
        SyntaxKind::ParenthesizedExpression,
        SyntaxKind::BinaryExpression,
        SyntaxKind::PrefixExpression,
        SyntaxKind::PostfixExpression,
        SyntaxKind::CastExpression,
        SyntaxKind::TernaryExpression,
        SyntaxKind::AssignmentExpression,
        SyntaxKind::NameExpression,
        SyntaxKind::CallExpression,
        SyntaxKind::MemberAccessExpression,
        SyntaxKind::ScopedAccessExpression,
        SyntaxKind::IndexExpression,
        SyntaxKind::ArrayExpression,
        SyntaxKind::ListExpression,
        SyntaxKind::InterpolatedString,
        SyntaxKind::HeredocExpression,
        SyntaxKind::ShellExecExpression,
        SyntaxKind::NewExpression,
        SyntaxKind::CloneExpression,
        SyntaxKind::IssetExpression,
        SyntaxKind::EmptyExpression,
        SyntaxKind::EvalExpression,
        SyntaxKind::ExitExpression,
        SyntaxKind::PrintExpression,
        SyntaxKind::ThrowExpression,
        SyntaxKind::YieldExpression,
        SyntaxKind::IncludeExpression,
        SyntaxKind::MatchExpression,
        SyntaxKind::ClosureExpression,
        SyntaxKind::ArrowFunctionExpression,
        SyntaxKind::Block,
        SyntaxKind::EmptyStatement,
        SyntaxKind::EchoStatement,
        SyntaxKind::ExpressionStatement,
        SyntaxKind::ReturnStatement,
        SyntaxKind::BreakStatement,
        SyntaxKind::ContinueStatement,
        SyntaxKind::GlobalStatement,
        SyntaxKind::StaticStatement,
        SyntaxKind::UnsetStatement,
        SyntaxKind::GotoStatement,
        SyntaxKind::LabelStatement,
        SyntaxKind::IfStatement,
        SyntaxKind::WhileStatement,
        SyntaxKind::DoWhileStatement,
        SyntaxKind::ForStatement,
        SyntaxKind::ForeachStatement,
        SyntaxKind::SwitchStatement,
        SyntaxKind::TryStatement,
        SyntaxKind::DeclareStatement,
        SyntaxKind::FunctionDeclaration,
        SyntaxKind::ConstantDeclaration,
        SyntaxKind::NamespaceDeclaration,
        SyntaxKind::UseDeclaration,
        SyntaxKind::ClassDeclaration,
        SyntaxKind::InterfaceDeclaration,
        SyntaxKind::TraitDeclaration,
        SyntaxKind::EnumDeclaration,
        SyntaxKind::NamedType,
        SyntaxKind::NullableType,
        SyntaxKind::UnionType,
        SyntaxKind::IntersectionType,
        SyntaxKind::ParenthesizedType,
        SyntaxKind::PropertyDeclaration,
        SyntaxKind::MethodDeclaration,
        SyntaxKind::TraitUseClause,
        SyntaxKind::EnumCase,
        SyntaxKind::SimpleInterpolation,
        SyntaxKind::BraceInterpolation,
        SyntaxKind::DollarBraceInterpolation,
        SyntaxKind::TraitPrecedence,
        SyntaxKind::TraitAlias,
        SyntaxKind::SourceFile,
        SyntaxKind::Name,
        SyntaxKind::ArgumentList,
        SyntaxKind::Argument,
        SyntaxKind::MemberName,
        SyntaxKind::ArrayElement,
        SyntaxKind::MatchArm,
        SyntaxKind::AttributeGroup,
        SyntaxKind::ParameterList,
        SyntaxKind::ClosureUseClause,
        SyntaxKind::Parameter,
        SyntaxKind::PropertyHookList,
        SyntaxKind::StaticVariable,
        SyntaxKind::ElseIfClause,
        SyntaxKind::ElseClause,
        SyntaxKind::ForExpressionList,
        SyntaxKind::SwitchCase,
        SyntaxKind::CatchClause,
        SyntaxKind::FinallyClause,
        SyntaxKind::DeclareDirective,
        SyntaxKind::ConstantElement,
        SyntaxKind::UseClause,
        SyntaxKind::UseGroup,
        SyntaxKind::ExtendsClause,
        SyntaxKind::ImplementsClause,
        SyntaxKind::MemberList,
        SyntaxKind::PropertyElement,
        SyntaxKind::TraitAdaptationList,
        SyntaxKind::PropertyHook,
        SyntaxKind::Attribute,
        SyntaxKind::ErrorNode,
    ];

    /// The inverse of [`SyntaxKind::into_raw`]. Total and panic-free:
    /// out-of-range values return `None`.
    pub fn from_raw(raw: u16) -> Option<Self> {
        Self::ALL.get(usize::from(raw)).copied()
    }

    /// The `u16` the tree stores; the discriminant.
    pub fn into_raw(self) -> u16 {
        self as u16
    }
}
